Attribute VB_Name = "mAPIconstants"
'»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
'» Module: mAPIconstants   File: mAPIconstants.bas   Author: TheFrogPrince@hotmail.com
'»
'» This module is the central repository for ALL windows constants
'» that pertain or relate to API calls, as well as a few of my own
'» types, enums, and constants.  If EXE size is an issue, many 3rd
'» party utilities exist that can strip out the unreferenced portions.
'»
'»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
'» CODE DEPENDECIES
'»==================
'»      NONE
'»
'»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
'» NOTES
'»=======
'»
'»
'»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
Option Explicit






'##############################################
'                 CONSTANTS
'##############################################
Public Const MAX_PATH = 400

Public Const WF_WINNT = &H4000&

Public Const sCompleteKeyboard = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890`-=\[];',./~!!@#$%^&*()_+{}:<>?" & """"

Public Const OFS_MAXPATHNAME = 128

Public Const GUID_OK As Long = 0
Public Const GUID_LENGTH As Long = 38


Public Const TV_FIRST = &H1100
Public Const TVM_GETNEXTITEM = (TV_FIRST + 10)
Public Const TVM_SELECTITEM = (TV_FIRST + 11)
Public Const TVGN_CARET = 9
Public Const TVGN_FIRSTVISIBLE = &H5

Public Const BDR_SUNKEN = &HA
Public Const BDR_OUTER = &H3
Public Const BDR_INNER = &HC
Public Const BDR_RAISED = &H5



'##############################################
'                   ENUMS
'##############################################

Public Enum enumLocaleInfoTypes
    LOCALE_ICENTURY = &H24
    LOCALE_ICOUNTRY = &H5
    LOCALE_ICURRDIGITS = &H19
    LOCALE_ICURRENCY = &H1B
    LOCALE_IDATE = &H21
    LOCALE_IDAYLZERO = &H26
    LOCALE_IDEFAULTCODEPAGE = &HB
    LOCALE_IDEFAULTCOUNTRY = &HA
    LOCALE_IDEFAULTLANGUAGE = &H9
    LOCALE_IDIGITS = &H11
    LOCALE_IINTLCURRDIGITS = &H1A
    LOCALE_ILANGUAGE = &H1
    LOCALE_ILDATE = &H22
    LOCALE_ILZERO = &H12
    LOCALE_IMEASURE = &HD
    LOCALE_IMONLZERO = &H27
    LOCALE_INEGCURR = &H1C
    LOCALE_INEGSEPBYSPACE = &H57
    LOCALE_INEGSIGNPOSN = &H53
    LOCALE_INEGSYMPRECEDES = &H56
    LOCALE_IPOSSEPBYSPACE = &H55
    LOCALE_IPOSSIGNPOSN = &H52
    LOCALE_IPOSSYMPRECEDES = &H54
    LOCALE_ITIME = &H23
    LOCALE_ITLZERO = &H25
    LOCALE_NOUSEROVERRIDE = &H80000000
    LOCALE_S1159 = &H28
    LOCALE_S2359 = &H29
    LOCALE_SABBREVCTRYNAME = &H7
    LOCALE_SABBREVDAYNAME1 = &H31
    LOCALE_SABBREVDAYNAME2 = &H32
    LOCALE_SABBREVDAYNAME3 = &H33
    LOCALE_SABBREVDAYNAME4 = &H34
    LOCALE_SABBREVDAYNAME5 = &H35
    LOCALE_SABBREVDAYNAME6 = &H36
    LOCALE_SABBREVDAYNAME7 = &H37
    LOCALE_SABBREVLANGNAME = &H3
    LOCALE_SABBREVMONTHNAME1 = &H44
    LOCALE_SABBREVMONTHNAME10 = &H4D
    LOCALE_SABBREVMONTHNAME11 = &H4E
    LOCALE_SABBREVMONTHNAME12 = &H4F
    LOCALE_SABBREVMONTHNAME13 = &H100F
    LOCALE_SABBREVMONTHNAME2 = &H45
    LOCALE_SABBREVMONTHNAME3 = &H46
    LOCALE_SABBREVMONTHNAME4 = &H47
    LOCALE_SABBREVMONTHNAME5 = &H48
    LOCALE_SABBREVMONTHNAME6 = &H49
    LOCALE_SABBREVMONTHNAME7 = &H4A
    LOCALE_SABBREVMONTHNAME8 = &H4B
    LOCALE_SABBREVMONTHNAME9 = &H4C
    LOCALE_SCOUNTRY = &H6
    LOCALE_SCURRENCY = &H14
    LOCALE_SDATE = &H1D
    LOCALE_SDAYNAME1 = &H2A
    LOCALE_SDAYNAME2 = &H2B
    LOCALE_SDAYNAME3 = &H2C
    LOCALE_SDAYNAME4 = &H2D
    LOCALE_SDAYNAME5 = &H2E
    LOCALE_SDAYNAME6 = &H2F
    LOCALE_SDAYNAME7 = &H30
    LOCALE_SDECIMAL = &HE
    LOCALE_SENGCOUNTRY = &H1002
    LOCALE_SENGLANGUAGE = &H1001
    LOCALE_SGROUPING = &H10
    LOCALE_SINTLSYMBOL = &H15
    LOCALE_SLANGUAGE = &H2
    LOCALE_SLIST = &HC
    LOCALE_SLONGDATE = &H20
    LOCALE_SMONDECIMALSEP = &H16
    LOCALE_SMONGROUPING = &H18
    LOCALE_SMONTHNAME1 = &H38
    LOCALE_SMONTHNAME10 = &H41
    LOCALE_SMONTHNAME11 = &H42
    LOCALE_SMONTHNAME12 = &H43
    LOCALE_SMONTHNAME2 = &H39
    LOCALE_SMONTHNAME3 = &H3A
    LOCALE_SMONTHNAME4 = &H3B
    LOCALE_SMONTHNAME5 = &H3C
    LOCALE_SMONTHNAME6 = &H3D
    LOCALE_SMONTHNAME7 = &H3E
    LOCALE_SMONTHNAME8 = &H3F
    LOCALE_SMONTHNAME9 = &H40
    LOCALE_SMONTHOUSANDSEP = &H17
    LOCALE_SNATIVECTRYNAME = &H8
    LOCALE_SNATIVEDIGITS = &H13
    LOCALE_SNATIVELANGNAME = &H4
    LOCALE_SNEGATIVESIGN = &H51
    LOCALE_SPOSITIVESIGN = &H50
    LOCALE_SSHORTDATE = &H1F
    LOCALE_STHOUSAND = &HF
    LOCALE_STIME = &H1E
    LOCALE_STIMEFORMAT = &H1003

End Enum




Public Enum enumFileShareMode
    FILE_SHARE_READ = &H1
    FILE_SHARE_WRITE = &H2
End Enum

Public Enum enumFileCreateDisposition
    CREATE_ALWAYS = 2
    CREATE_NEW = 1
    OPEN_EXISTING = 3
    OPEN_ALWAYS = 4
    TRUNCATE_EXISTING = 5
End Enum

Public Enum enumFileDesiredAccess
    DEVICE_QUERY_ONLY = 0
    SPECIFIC_RIGHTS_ALL = &HFFFF
    GENERIC_ALL = &H10000000
    GENERIC_READ = &H80000000
    GENERIC_WRITE = &H40000000
    GENERIC_EXECUTE = &H20000000
    Delete = &H10000
    WRITE_DAC = &H40000
    WRITE_OWNER = &H80000
    Synchronize = &H100000
    STANDARD_RIGHTS_ALL = &H1F0000
    READ_CONTROL = &H20000
    STANDARD_RIGHTS_EXECUTE = (READ_CONTROL)
    STANDARD_RIGHTS_READ = (READ_CONTROL)
    STANDARD_RIGHTS_REQUIRED = &HF0000
    STANDARD_RIGHTS_WRITE = (READ_CONTROL)
    ACCESS_SYSTEM_SECURITY = &H1000000
    MAXIMUM_ALLOWED = &H2000000
End Enum

Public Enum GET_FILEEX_INFO_LEVELS
    GetFileExInfoStandard = 1
    GetFileExMaxInfoLevel = 2
End Enum




Public Enum enumDrawTextFormats
    [DT_BOTTOM] = &H8
    [DT_CALCRECT] = &H400
    [DT_CENTER] = &H1
    [DT_EXPANDTABS] = &H40
    [DT_EXTERNALLEADING] = &H200
    [DT_INTERNAL] = &H1000
    [DT_LEFT] = &H0
    [DT_NOCLIP] = &H100
    [DT_NOPREFIX] = &H800
    [DT_RIGHT] = &H2
    [DT_SINGLELINE] = &H20
    [DT_TABSTOP] = &H80
    [DT_TOP] = &H0
    [DT_VCENTER] = &H4
    [DT_WORDBREAK] = &H10
End Enum





Public Enum enumFileOps
    [FO_COPY] = &H2
    [FO_DELETE] = &H3
    [FO_MOVE] = &H1
    [FO_RENAME] = &H4
End Enum

Public Enum enumFileOpFlags
    [FOF_ALLOWUNDO] = &H40
    [FOF_SILENT] = &H4
    [FOF_NOCONFIRMATION] = &H10
    [FOF_RENAMEONCOLLISION] = &H8
    [FOF_NOCONFIRMMKDIR] = &H200
    [FOF_FILESONLY] = &H80
End Enum





Public Enum enumBrowseForFlags
    [BIF_BROWSEFORCOMPUTER] = &H1000
    [BIF_BROWSEFORPRINTER] = &H2000
    [BIF_BROWSEINCLUDEFILES] = &H4000
    [BIF_DONTGOBELOWDOMAIN] = &H2
    [BIF_RETURNFSANCESTORS] = &H8
    [BIF_RETURNONLYFSDIRS] = &H1
    [BIF_STATUSTEXT] = &H4
    [BIF_NONESPECIFIED] = 0
End Enum








Public Enum enumEditStyles
    ES_AUTOHSCROLL = &H80&
    ES_AUTOVSCROLL = &H40&
    ES_CENTER = &H1&
    ES_LEFT = &H0&
    ES_LOWERCASE = &H10&
    ES_MULTILINE = &H4&
    ES_NOHIDESEL = &H100&
    ES_OEMCONVERT = &H400&
    ES_PASSWORD = &H20&
    ES_READONLY = &H800&
    ES_RIGHT = &H2&
    ES_UPPERCASE = &H8&
    ES_WANTRETURN = &H1000&
End Enum

Public Enum enumTextAlignment
    TA_BASELINE = 24
    TA_BOTTOM = 8
    TA_CENTER = 6
    TA_LEFT = 0
    TA_NOUPDATECP = 0
    TA_RIGHT = 2
    TA_TOP = 0
    TA_UPDATECP = 1
    TA_MASK = (TA_BASELINE + TA_CENTER + TA_UPDATECP)
End Enum





Public Enum enumExtendedWindowStyles
    WS_EX_ACCEPTFILES = &H10&
    WS_EX_DLGMODALFRAME = &H1&
    WS_EX_NOPARENTNOTIFY = &H4&
    WS_EX_TOPMOST = &H8&
    WS_EX_TRANSPARENT = &H20&
    WS_EX_CLIENTEDGE = &H200
    WS_EX_STATICEDGE = &H20000
End Enum


Public Enum enumSetWindowsPos
    SWP_FRAMECHANGED = &H20
    SWP_HIDEWINDOW = &H80
    SWP_NOACTIVATE = &H10
    SWP_NOCOPYBITS = &H100
    SWP_NOMOVE = &H2
    SWP_NOOWNERZORDER = &H200
    SWP_NOREDRAW = &H8
    SWP_NOSIZE = &H1
    SWP_NOZORDER = &H4
    SWP_SHOWWINDOW = &H40
    SWP_DRAWFRAME = SWP_FRAMECHANGED
    SWP_NOREPOSITION = SWP_NOOWNERZORDER
    Flags = SWP_NOMOVE Or SWP_NOSIZE
    HWND_NOTOPMOST = -2
    HWND_TOPMOST = -1
    
End Enum


'/* Image type */
Public Enum enumDrawStateImageTypes
    DST_COMPLEX = &H0
    DST_TEXT = &H1
    DST_PREFIXTEXT = &H2
    DST_ICON = &H3
    DST_BITMAP = &H4
End Enum

    ' /* State type */
Public Enum enumDrawStateTypes
    DSS_NORMAL = &H0
    DSS_UNION = &H10 ' Dither
    DSS_DISABLED = &H20
    DSS_MONO = &H80 ' Draw in colour of brush specified in hBrush
    DSS_RIGHT = &H8000
End Enum

Public Enum enumBitBltOps
    BLACKNESS = &H42
    DSTINVERT = &H550009
    MERGECOPY = &HC000CA
    NOTSRCCOPY = &H330008
    NOTSRCERASE = &H1100A6
    PATCOPY = &HF00021
    PATINVERT = &H5A0049
    PATPAINT = &HFB0A09
    SRCAND = &H8800C6
    SRCCOPY = &HCC0020
    SRCERASE = &H440328
    SRCINVERT = &H660046
    SRCPAINT = &HEE0086
    WHITENESS = &HFF0062
End Enum

Public Enum enumMouseEvents
    MOUSEEVENTF_ABSOLUTE = &H8000
    MOUSEEVENTF_LEFTUP = &H4
    MOUSEEVENTF_LEFTDOWN = &H2
    MOUSEEVENTF_MIDDLEDOWN = &H20
    MOUSEEVENTF_MIDDLEUP = &H40
    MOUSEEVENTF_MOVE = &H1
    MOUSEEVENTF_RIGHTDOWN = &H8
    MOUSEEVENTF_RIGHTUP = &H10
    

End Enum

#If Not bStandAloneControls Then
Public Enum enumBorderFlags
    BF_ADJUST = &H2000
    BF_BOTTOM = &H8
    BF_DIAGONAL = &H10
    BF_FLAT = &H4000
    BF_LEFT = &H1
    BF_MIDDLE = &H800
    BF_MONO = &H8000
    BF_RIGHT = &H4
    BF_SOFT = &H1000
    BF_TOP = &H2
    BF_BOTTOMLEFT = (BF_BOTTOM Or BF_LEFT)
    BF_BOTTOMRIGHT = (BF_BOTTOM Or BF_RIGHT)
    BF_DIAGONAL_ENDBOTTOMLEFT = (BF_DIAGONAL Or BF_BOTTOM Or BF_LEFT)
    BF_DIAGONAL_ENDBOTTOMRIGHT = (BF_DIAGONAL Or BF_BOTTOM Or BF_RIGHT)
    BF_DIAGONAL_ENDTOPLEFT = (BF_DIAGONAL Or BF_TOP Or BF_LEFT)
    BF_DIAGONAL_ENDTOPRIGHT = (BF_DIAGONAL Or BF_TOP Or BF_RIGHT)
    BF_RECT = (BF_LEFT Or BF_TOP Or BF_RIGHT Or BF_BOTTOM)
    BF_TOPLEFT = (BF_TOP Or BF_LEFT)
    BF_TOPRIGHT = (BF_TOP Or BF_RIGHT)
End Enum
Public Enum enumBorderEdges
    BDR_RAISEDINNER = &H4
    BDR_RAISEDOUTER = &H1
    BDR_SUNKENINNER = &H8
    BDR_SUNKENOUTER = &H2
    EDGE_BUMP = (BDR_RAISEDOUTER Or BDR_SUNKENINNER)
    EDGE_ETCHED = (BDR_SUNKENOUTER Or BDR_RAISEDINNER)
    EDGE_RAISED = (BDR_RAISEDOUTER Or BDR_RAISEDINNER)
    EDGE_SUNKEN = (BDR_SUNKENOUTER Or BDR_SUNKENINNER)
End Enum
#End If




Public Enum enumRegHkeys
    HKEY_CLASSES_ROOT = &H80000000
    HKEY_CURRENT_CONFIG = &H80000005
    HKEY_CURRENT_USER = &H80000001
    HKEY_DYN_DATA = &H80000006
    HKEY_LOCAL_MACHINE = &H80000002
    HKEY_PERFORMANCE_DATA = &H80000004
    HKEY_USERS = &H80000003
End Enum

Public Enum enumDriveTypes
    DRIVE_CDROM = 5
    DRIVE_FIXED = 3
    DRIVE_RAMDISK = 6
    DRIVE_REMOTE = 4
    DRIVE_REMOVABLE = 2
End Enum

Public Enum enumAppBarEdges
    ABE_BOTTOM = 3
    ABE_LEFT = 0
    ABE_RIGHT = 2
    ABE_TOP = 1
    ABE_FLOATING = -1
End Enum

Public Enum enumAppBarMessages
    ABM_ACTIVATE = &H6
    ABM_GETAUTOHIDEBAR = &H7
    ABM_GETSTATE = &H4
    ABM_GETTASKBARPOS = &H5
    ABM_NEW = &H0
    ABM_QUERYPOS = &H2
    ABM_REMOVE = &H1
    ABM_SETAUTOHIDEBAR = &H8
    ABM_SETPOS = &H3
    ABM_WINDOWPOSCHANGED = &H9
End Enum

Public Enum enumAppBarStates
    ABS_ALWAYSONTOP = &H2
    ABS_AUTOHIDE = &H1
End Enum

Public Enum enumAppBarNotifications
    ABN_FULLSCREENAPP = &H2
    ABN_POSCHANGED = &H1
    ABN_STATECHANGE = &H0
    ABN_WINDOWARRANGE = &H3
End Enum

#If Not bComObject Then
Public Enum enumSysColors
    COLOR_ACTIVEBORDER = 10
    COLOR_ACTIVECAPTION = 2
    COLOR_ADJ_MAX = 100
    COLOR_ADJ_MIN = -100
    COLOR_APPWORKSPACE = 12
    COLOR_BACKGROUND = 1
    COLOR_BTNFACE = 15
    COLOR_BTNHIGHLIGHT = 20
    COLOR_BTNSHADOW = 16
    COLOR_BTNTEXT = 18
    COLOR_CAPTIONTEXT = 9
    COLOR_GRAYTEXT = 17
    COLOR_HIGHLIGHT = 13
    COLOR_HIGHLIGHTTEXT = 14
    COLOR_INACTIVEBORDER = 11
    COLOR_INACTIVECAPTION = 3
    COLOR_INACTIVECAPTIONTEXT = 19
    COLOR_MENU = 4
    COLOR_MENUTEXT = 7
    COLOR_SCROLLBAR = 0
    COLOR_WINDOW = 5
    COLOR_WINDOWFRAME = 6
    COLOR_WINDOWTEXT = 8
End Enum
#End If

Public Enum enumFileFlags
    FILE_FLAG_BACKUP_SEMANTICS = &H2000000
    FILE_FLAG_DELETE_ON_CLOSE = &H4000000
    FILE_FLAG_NO_BUFFERING = &H20000000
    FILE_FLAG_OVERLAPPED = &H40000000
    FILE_FLAG_POSIX_SEMANTICS = &H1000000
    FILE_FLAG_RANDOM_ACCESS = &H10000000
    FILE_FLAG_SEQUENTIAL_SCAN = &H8000000
    FILE_FLAG_WRITE_THROUGH = &H80000000
End Enum









Public Enum enumTimeElapsedFormats
    etfHoursMinutesSeconds = 1
    etfLCD = 2
    
End Enum


Public Enum enumButtonStyles
    BS_3STATE = &H5&
    BS_AUTO3STATE = &H6&
    BS_AUTOCHECKBOX = &H3&
    BS_AUTORADIOBUTTON = &H9&
    BS_CHECKBOX = &H2&
    BS_DEFPUSHBUTTON = &H1&
    BS_DIBPATTERN = 5
    BS_DIBPATTERN8X8 = 8
    BS_DIBPATTERNPT = 6
    BS_GROUPBOX = &H7&
    BS_HATCHED = 2
    BS_NULL = 1
    BS_HOLLOW = BS_NULL
    BS_INDEXED = 4
    BS_LEFTTEXT = &H20&
    BS_OWNERDRAW = &HB&
    BS_PATTERN = 3
    BS_PATTERN8X8 = 7
    BS_PUSHBUTTON = &H0&
    BS_RADIOBUTTON = &H4&
    BS_SOLID = 0
    BS_USERBUTTON = &H8&
    
    BS_ICON = &H40&
    BS_BITMAP = &H80&
    BS_LEFT = &H100&
    BS_RIGHT = &H200&
    BS_CENTER = &H300&
    BS_TOP = &H400&
    BS_BOTTOM = &H800&
    BS_VCENTER = &HC00&
    BS_PUSHLIKE = &H1000&
    BS_MULTILINE = &H2000&
    BS_NOTIFY = &H4000&
    BS_FLAT = &H8000&
    BS_RIGHTBUTTON = BS_LEFTTEXT
End Enum

Public Enum enumWindowsMessages
    
    EM_CANUNDO = &HC6
    EM_EMPTYUNDOBUFFER = &HCD
    EM_FMTLINES = &HC8
    EM_GETFIRSTVISIBLELINE = &HCE
    EM_GETHANDLE = &HBD
    EM_GETLINE = &HC4
    EM_GETLINECOUNT = &HBA
    EM_GETMODIFY = &HB8
    EM_GETPASSWORDCHAR = &HD2
    EM_GETRECT = &HB2
    EM_GETSEL = &HB0
    EM_GETTHUMB = &HBE
    EM_GETWORDBREAKPROC = &HD1
    EM_LIMITTEXT = &HC5
    EM_LINEFROMCHAR = &HC9
    EM_LINEINDEX = &HBB
    EM_LINELENGTH = &HC1
    EM_LINESCROLL = &HB6
    EM_REPLACESEL = &HC2
    EM_SCROLL = &HB5
    EM_SCROLLCARET = &HB7
    EM_SETHANDLE = &HBC
    EM_SETMODIFY = &HB9
    EM_SETPASSWORDCHAR = &HCC
    EM_SETREADONLY = &HCF
    EM_SETRECT = &HB3
    EM_SETRECTNP = &HB4
    EM_SETSEL = &HB1
    EM_SETTABSTOPS = &HCB
    EM_SETWORDBREAKPROC = &HD0
    EM_UNDO = &HC7
    
    BM_GETCHECK = &HF0
    BM_GETSTATE = &HF2
    BM_SETCHECK = &HF1
    BM_SETSTATE = &HF3
    BM_SETSTYLE = &HF4
    CB_SHOWDROPDOWN = &H14F
    CB_GETDROPPEDSTATE = &H157
    CB_LIMITTEXT = &H141
    CB_SELECTSTRING = &H14D
    CB_FINDSTRING = &H14C
    CB_FINDSTRINGEXACT = &H158
    WM_USER = &H400
    WM_ACTIVATE = &H6
    WM_ACTIVATEAPP = &H1C
    WM_ASKCBFORMATNAME = &H30C
    WM_CANCELJOURNAL = &H4B
    WM_CANCELMODE = &H1F
    WM_CHANGECBCHAIN = &H30D
    WM_CHAR = &H102
    WM_CHARTOITEM = &H2F
    WM_CHILDACTIVATE = &H22
    WM_CHOOSEFONT_GETLOGFONT = (WM_USER + 1)
    WM_CHOOSEFONT_SETFLAGS = (WM_USER + 102)
    WM_CHOOSEFONT_SETLOGFONT = (WM_USER + 101)
    WM_CLEAR = &H303
    WM_CLOSE = &H10
    WM_COMMAND = &H111
    WM_COMMNOTIFY = &H44
    WM_COMPACTING = &H41
    WM_COMPAREITEM = &H39
    WM_CONTEXTMENU = &H7B
    WM_CONVERTREQUESTEX = &H108
    WM_COPY = &H301
    WM_COPYDATA = &H4A
    WM_CREATE = &H1
    WM_CTLCOLORBTN = &H135
    WM_CTLCOLORDLG = &H136
    WM_CTLCOLOREDIT = &H133
    WM_CTLCOLORLISTBOX = &H134
    WM_CTLCOLORMSGBOX = &H132
    WM_CTLCOLORSCROLLBAR = &H137
    WM_CTLCOLORSTATIC = &H138
    WM_CUT = &H300
    WM_DDE_FIRST = &H3E0
    WM_DDE_ACK = (WM_DDE_FIRST + 4)
    WM_DDE_ADVISE = (WM_DDE_FIRST + 2)
    WM_DDE_DATA = (WM_DDE_FIRST + 5)
    WM_DDE_EXECUTE = (WM_DDE_FIRST + 8)
    WM_DDE_INITIATE = (WM_DDE_FIRST)
    WM_DDE_LAST = (WM_DDE_FIRST + 8)
    WM_DDE_POKE = (WM_DDE_FIRST + 7)
    WM_DDE_REQUEST = (WM_DDE_FIRST + 6)
    WM_DDE_TERMINATE = (WM_DDE_FIRST + 1)
    WM_DDE_UNADVISE = (WM_DDE_FIRST + 3)
    WM_DEADCHAR = &H103
    WM_DELETEITEM = &H2D
    WM_DESTROY = &H2
    WM_DESTROYCLIPBOARD = &H307
    WM_DEVMODECHANGE = &H1B
    WM_DRAWCLIPBOARD = &H308
    WM_DRAWITEM = &H2B
    WM_DROPFILES = &H233
    WM_ENABLE = &HA
    WM_ENDSESSION = &H16
    WM_ENTERIDLE = &H121
    WM_ENTERMENULOOP = &H211
    WM_ERASEBKGND = &H14
    WM_EXITMENULOOP = &H212
    WM_FONTCHANGE = &H1D
    WM_GETDLGCODE = &H87
    WM_GETFONT = &H31
    WM_GETHOTKEY = &H33
    WM_GETMINMAXINFO = &H24
    WM_GETTEXT = &HD
    WM_GETTEXTLENGTH = &HE
    WM_HOTKEY = &H312
    WM_HSCROLL = &H114
    WM_HSCROLLCLIPBOARD = &H30E
    WM_ICONERASEBKGND = &H27
    WM_IME_CHAR = &H286
    WM_IME_COMPOSITION = &H10F
    WM_IME_COMPOSITIONFULL = &H284
    WM_IME_CONTROL = &H283
    WM_IME_ENDCOMPOSITION = &H10E
    WM_IME_KEYDOWN = &H290
    WM_IME_KEYLAST = &H10F
    WM_IME_KEYUP = &H291
    WM_IME_NOTIFY = &H282
    WM_IME_SELECT = &H285
    WM_IME_SETCONTEXT = &H281
    WM_IME_STARTCOMPOSITION = &H10D
    WM_INITDIALOG = &H110
    WM_INITMENU = &H116
    WM_INITMENUPOPUP = &H117
    WM_KEYDOWN = &H100
    WM_KEYFIRST = &H100
    WM_KEYLAST = &H108
    WM_KEYUP = &H101
    WM_KILLFOCUS = &H8
    WM_LBUTTONDBLCLK = &H203
    WM_LBUTTONDOWN = &H201
    WM_LBUTTONUP = &H202
    WM_MBUTTONDBLCLK = &H209
    WM_MBUTTONDOWN = &H207
    WM_MBUTTONUP = &H208
    WM_MDIACTIVATE = &H222
    WM_MDICASCADE = &H227
    WM_MDICREATE = &H220
    WM_MDIDESTROY = &H221
    WM_MDIGETACTIVE = &H229
    WM_MDIICONARRANGE = &H228
    WM_MDIMAXIMIZE = &H225
    WM_MDINEXT = &H224
    WM_MDIREFRESHMENU = &H234
    WM_MDIRESTORE = &H223
    WM_MDISETMENU = &H230
    WM_MDITILE = &H226
    WM_MEASUREITEM = &H2C
    WM_MENUCHAR = &H120
    WM_MENUSELECT = &H11F
    WM_MOUSEACTIVATE = &H21
    WM_MOUSEFIRST = &H200
    WM_MOUSELAST = &H209
    WM_MOUSEMOVE = &H200
    WM_MOVE = &H3
    WM_NCACTIVATE = &H86
    WM_NCCALCSIZE = &H83
    WM_NCCREATE = &H81
    WM_NCDESTROY = &H82
    WM_NCHITTEST = &H84
    WM_NCLBUTTONDBLCLK = &HA3
    WM_NCLBUTTONDOWN = &HA1
    WM_NCLBUTTONUP = &HA2
    WM_NCMBUTTONDBLCLK = &HA9
    WM_NCMBUTTONDOWN = &HA7
    WM_NCMBUTTONUP = &HA8
    WM_NCMOUSEMOVE = &HA0
    WM_NCPAINT = &H85
    WM_NCRBUTTONDBLCLK = &HA6
    WM_NCRBUTTONDOWN = &HA4
    WM_NCRBUTTONUP = &HA5
    WM_NEXTDLGCTL = &H28
    WM_NULL = &H0
    WM_OTHERWINDOWCREATED = &H42
    WM_OTHERWINDOWDESTROYED = &H43
    WM_PAINT = &HF
    WM_PAINTCLIPBOARD = &H309
    WM_PAINTICON = &H26
    WM_PALETTECHANGED = &H311
    WM_PALETTEISCHANGING = &H310
    WM_PARENTNOTIFY = &H210
    WM_PASTE = &H302
    WM_PENWINFIRST = &H380
    WM_PENWINLAST = &H38F
    WM_POWER = &H48
    WM_PSD_ENVSTAMPRECT = (WM_USER + 5)
    WM_PSD_FULLPAGERECT = (WM_USER + 1)
    WM_PSD_GREEKTEXTRECT = (WM_USER + 4)
    WM_PSD_MARGINRECT = (WM_USER + 3)
    WM_PSD_MINMARGINRECT = (WM_USER + 2)
    WM_PSD_PAGESETUPDLG = (WM_USER)
    WM_PSD_YAFULLPAGERECT = (WM_USER + 6)
    WM_QUERYDRAGICON = &H37
    WM_QUERYENDSESSION = &H11
    WM_QUERYNEWPALETTE = &H30F
    WM_QUERYOPEN = &H13
    WM_QUEUESYNC = &H23
    WM_QUIT = &H12
    WM_RBUTTONDBLCLK = &H206
    WM_RBUTTONDOWN = &H204
    WM_RBUTTONUP = &H205
    WM_RENDERALLFORMATS = &H306
    WM_RENDERFORMAT = &H305
    WM_SETCURSOR = &H20
    WM_SETFOCUS = &H7
    WM_SETFONT = &H30
    WM_SETHOTKEY = &H32
    WM_SETREDRAW = &HB
    WM_SETTEXT = &HC
    WM_SHOWWINDOW = &H18
    WM_SIZE = &H5
    WM_SIZECLIPBOARD = &H30B
    WM_SPOOLERSTATUS = &H2A
    WM_SYSCHAR = &H106
    WM_SYSCOLORCHANGE = &H15
    WM_SYSCOMMAND = &H112
    WM_SYSDEADCHAR = &H107
    WM_SYSKEYDOWN = &H104
    WM_SYSKEYUP = &H105
    WM_TIMECHANGE = &H1E
    WM_TIMER = &H113
    WM_UNDO = &H304
    WM_VKEYTOITEM = &H2E
    WM_VSCROLL = &H115
    WM_VSCROLLCLIPBOARD = &H30A
    WM_WINDOWPOSCHANGED = &H47
    WM_WINDOWPOSCHANGING = &H46
    WM_WININICHANGE = &H1A
End Enum




Public Enum enumSecondsTypes
    estSinceMidnight = 1
    estSinceBeginningOfWeek = 2
    estSinceFirstOfTheMonth = 3
    estSinceFirstOfTheYear = 4
    estSinceZero = 5
End Enum


'------------------------------------------------------
' List of your primary RGB colors.
' Goes with the function GetRGBValue()
Public Enum enumRGBbases
    rgbRed = 1
    rgbBlue = 2
    rgbGreen = 4
End Enum


'------------------------------------------------------
' A list of possible OLE data types dropped
Public Enum enumOLEDATATYPES
    OLEObjectHasFiles = 15
    ShellControlFileObject = -12908
    WindowsExplorerNetworkNeighborhoodObject = -12900
    WindowsExplorerNetworkNeighborhoodFileObject = -12908
    WindowsExplorerObject = -12845
    WindowsExplorerLocalObject = -14763
    WindowsExplorerLocalFileObject = -12908
    
End Enum





'------------------------------------------------------
' A list of possible ways to check a string.
Public Enum enumStringIsTypes
    esiOnlyNumbers = 1
    esiNumbersAndMoneyPunctuation = 2
    esiNumbersAndNumericPunctuation = 3
    esiMathematicalCharacters = 4
    
End Enum


'    vbWindowText
'    vbWindowFrame
'    vbWindowBackground
'    vbTitleBarText
'    vbScrollBars
'    vbMenuText
'    vbMenuBar
'    vbInfoText
'    vbInfoBackground
'    vbInactiveTitleBarText
'    vbInactiveTitleBar
'    vbInactiveCaptionText
'    vbInactiveBorder
'    vbHighlightText
'    vbHighlight
'    vbGrayText
'    vbDesktop
'    vbButtonText
'    vbButtonShadow
'    vbButtonFace
'    vbApplicationWorkspace
'    vbActiveTitleBarText
'    vbActiveTitleBar
'    vbActiveBorder
'    vb3DShadow
'    vb3DLight
'    vb3DHighlight
'    vb3DFace
'    vb3DDKShadow
Public Enum enumColors
    [ecRed] = vbRed
    [ecOrange] = &H80FF&
    [ecYellow] = vbYellow
    [ecGreen] = vbGreen
    [ecBlue] = vbBlue
    [ecCyan] = vbCyan
    [ecBlack] = vbBlack
    [ecMagenta] = vbMagenta
    [ecWhite] = vbWhite
    [ecPurple] = &HC000C0
    [ecDarkPurple] = &H800080
    
End Enum

Public Enum enumVIrtualKeys
    VK_ADD = &H6B
    VK_ATTN = &HF6
    VK_BACK = &H8
    VK_CANCEL = &H3
    VK_CAPITAL = &H14
    VK_CLEAR = &HC
    VK_CONTROL = &H11
    VK_CRSEL = &HF7
    VK_DECIMAL = &H6E
    VK_DELETE = &H2E
    VK_DIVIDE = &H6F
    VK_DOWN = &H28
    VK_END = &H23
    VK_EREOF = &HF9
    VK_ESCAPE = &H1B
    VK_EXECUTE = &H2B
    VK_EXSEL = &HF8
    VK_F1 = &H70
    VK_F10 = &H79
    VK_F11 = &H7A
    VK_F12 = &H7B
    VK_F13 = &H7C
    VK_F14 = &H7D
    VK_F15 = &H7E
    VK_F16 = &H7F
    VK_F17 = &H80
    VK_F18 = &H81
    VK_F19 = &H82
    VK_F2 = &H71
    VK_F20 = &H83
    VK_F21 = &H84
    VK_F22 = &H85
    VK_F23 = &H86
    VK_F24 = &H87
    VK_F3 = &H72
    VK_F4 = &H73
    VK_F5 = &H74
    VK_F6 = &H75
    VK_F7 = &H76
    VK_F8 = &H77
    VK_F9 = &H78
    VK_HELP = &H2F
    VK_HOME = &H24
    VK_INSERT = &H2D
    VK_LBUTTON = &H1
    VK_LCONTROL = &HA2
    VK_LEFT = &H25
    VK_LMENU = &HA4
    VK_LSHIFT = &HA0
    VK_MBUTTON = &H4
    VK_MENU = &H12
    VK_MULTIPLY = &H6A
    VK_NEXT = &H22
    VK_NONAME = &HFC
    VK_NUMLOCK = &H90
    VK_NUMPAD0 = &H60
    VK_NUMPAD1 = &H61
    VK_NUMPAD2 = &H62
    VK_NUMPAD3 = &H63
    VK_NUMPAD4 = &H64
    VK_NUMPAD5 = &H65
    VK_NUMPAD6 = &H66
    VK_NUMPAD7 = &H67
    VK_NUMPAD8 = &H68
    VK_NUMPAD9 = &H69
    VK_OEM_CLEAR = &HFE
    VK_PA1 = &HFD
    VK_PAUSE = &H13
    VK_PLAY = &HFA
    VK_PRINT = &H2A
    VK_PRIOR = &H21
    VK_PROCESSKEY = &HE5
    VK_RBUTTON = &H2
    VK_RCONTROL = &HA3
    VK_RETURN = &HD
    VK_RIGHT = &H27
    VK_RMENU = &HA5
    VK_RSHIFT = &HA1
    VK_SCROLL = &H91
    VK_SELECT = &H29
    VK_SEPARATOR = &H6C
    VK_SHIFT = &H10
    VK_SNAPSHOT = &H2C
    VK_SPACE = &H20
    VK_SUBTRACT = &H6D
    VK_TAB = &H9
    VK_UP = &H26
    VK_ZOOM = &HFB
End Enum

Public Enum enumSystemMetrics
    SM_CMETRICS = 44
    SM_CMOUSEBUTTONS = 43
    SM_CXBORDER = 5
    SM_CXCURSOR = 13
    SM_CXDLGFRAME = 7
    SM_CXDOUBLECLK = 36
    SM_CXFIXEDFRAME = SM_CXDLGFRAME
    SM_CXFRAME = 32
    SM_CXFULLSCREEN = 16
    SM_CXHSCROLL = 21
    SM_CXHTHUMB = 10
    SM_CXICON = 11
    SM_CXICONSPACING = 38
    SM_CXMIN = 28
    SM_CXMINTRACK = 34
    SM_CXSCREEN = 0
    SM_CXSIZE = 30
    SM_CXSIZEFRAME = SM_CXFRAME
    SM_CXVSCROLL = 2
    SM_CYBORDER = 6
    SM_CYCAPTION = 4
    SM_CYCURSOR = 14
    SM_CYDLGFRAME = 8
    SM_CYDOUBLECLK = 37
    SM_CYFIXEDFRAME = SM_CYDLGFRAME
    SM_CYFRAME = 33
    SM_CYFULLSCREEN = 17
    SM_CYHSCROLL = 3
    SM_CYICON = 12
    SM_CYICONSPACING = 39
    SM_CYKANJIWINDOW = 18
    SM_CYMENU = 15
    SM_CYMIN = 29
    SM_CYMINTRACK = 35
    SM_CYSCREEN = 1
    SM_CYSIZE = 31
    SM_CYSIZEFRAME = SM_CYFRAME
    SM_CYVSCROLL = 20
    SM_CYVTHUMB = 9
    SM_DBCSENABLED = 42
    SM_MENUDROPALIGNMENT = 40
    SM_MOUSEPRESENT = 19
    SM_PENWINDOWS = 41
    SM_RESERVED1 = 24
    SM_RESERVED2 = 25
    SM_RESERVED3 = 26
    SM_RESERVED4 = 27
    SM_SWAPBUTTON = 23
End Enum




Public Enum enumFileNameParts
    efpFileName = 2 ^ 0
    efpFileExt = 2 ^ 1
    efpFilePath = 2 ^ 2
    efpFileNameAndExt = efpFileName + efpFileExt
    efpFileNameAndPath = efpFilePath + efpFileName
    
End Enum


Public Enum enumAPIerrors
'    ERROR_ACCESS_DENIED = 5&
'    ERROR_ACCOUNT_DISABLED = 1331&
'    ERROR_ACCOUNT_EXPIRED = 1793&
'    ERROR_ACCOUNT_RESTRICTION = 1327&
'    ERROR_ADAP_HDW_ERR = 57&
'    ERROR_ALIAS_EXISTS = 1379&
'    ERROR_ALLOTTED_SPACE_EXCEEDED = 1344&
'    ERROR_ALREADY_ASSIGNED = 85&
'    ERROR_ALREADY_EXISTS = 183&
'    ERROR_ALREADY_RUNNING_LKG = 1074&
'    ERROR_ALREADY_WAITING = 1904&
'    ERROR_ARENA_TRASHED = 7&
'    ERROR_ARITHMETIC_OVERFLOW = 534&
'    ERROR_ATOMIC_LOCKS_NOT_SUPPORTED = 174&
'    ERROR_AUTODATASEG_EXCEEDS_64k = 199&
'    ERROR_BAD_ARGUMENTS = 160&
'    ERROR_BAD_COMMAND = 22&
'    ERROR_BAD_DESCRIPTOR_FORMAT = 1361&
'    ERROR_BAD_DEV_TYPE = 66&
'    ERROR_BAD_DEVICE = 1200&
'    ERROR_BAD_DRIVER = 2001
'    ERROR_BAD_DRIVER_LEVEL = 119&
'    ERROR_BAD_ENVIRONMENT = 10&
'    ERROR_BAD_EXE_FORMAT = 193&
    ERROR_BAD_FORMAT = 11&
'    ERROR_BAD_IMPERSONATION_LEVEL = 1346&
'    ERROR_BAD_INHERITANCE_ACL = 1340&
'    ERROR_BAD_LENGTH = 24&
'    ERROR_BAD_LOGON_SESSION_STATE = 1365&
'    ERROR_BAD_NET_NAME = 67&
'    ERROR_BAD_NET_RESP = 58&
'    ERROR_BAD_NETPATH = 53&
'    ERROR_BAD_PATHNAME = 161&
'    ERROR_BAD_PIPE = 230&
'    ERROR_BAD_PROFILE = 1206&
'    ERROR_BAD_PROVIDER = 1204&
'    ERROR_BAD_REM_ADAP = 60&
'    ERROR_BAD_THREADID_ADDR = 159&
'    ERROR_BAD_TOKEN_TYPE = 1349&
'    ERROR_BAD_UNIT = 20&
'    ERROR_BAD_USERNAME = 2202&
'    ERROR_BAD_VALIDATION_CLASS = 1348&
'    ERROR_BADDB = 1009&
'    ERROR_BADKEY = 1010&
'    ERROR_BEGINNING_OF_MEDIA = 1102&
'    ERROR_BOOT_ALREADY_ACCEPTED = 1076&
'    ERROR_BROKEN_PIPE = 109&
'    ERROR_BUFFER_OVERFLOW = 111&
'    ERROR_BUS_RESET = 1111&
'    ERROR_BUSY = 170&
'    ERROR_BUSY_DRIVE = 142&
'    ERROR_CALL_NOT_IMPLEMENTED = 120&
'    ERROR_CAN_NOT_COMPLETE = 1003&
'    ERROR_CAN_NOT_DEL_LOCAL_WINS = 4001
'    ERROR_CANCEL_VIOLATION = 173&
'    ERROR_CANNOT_COPY = 266&
'    ERROR_CANNOT_FIND_WND_CLASS = 1407&
'    ERROR_CANNOT_IMPERSONATE = 1368&
'    ERROR_CANNOT_MAKE = 82&
'    ERROR_CANNOT_OPEN_PROFILE = 1205&
'    ERROR_CANT_ACCESS_DOMAIN_INFO = 1351&
'    ERROR_CANT_DISABLE_MANDATORY = 1310&
'    ERROR_CANT_OPEN_ANONYMOUS = 1347&
'    ERROR_CANTOPEN = 1011&
'    ERROR_CANTREAD = 1012&
'    ERROR_CANTWRITE = 1013&
'    ERROR_CHILD_MUST_BE_VOLATILE = 1021&
'    ERROR_CHILD_NOT_COMPLETE = 129&
'    ERROR_CHILD_WINDOW_MENU = 1436&
'    ERROR_CIRCULAR_DEPENDENCY = 1059&
'    ERROR_CLASS_ALREADY_EXISTS = 1410&
'    ERROR_CLASS_DOES_NOT_EXIST = 1411&
'    ERROR_CLASS_HAS_WINDOWS = 1412&
'    ERROR_CLIPBOARD_NOT_OPEN = 1418&
'    ERROR_CLIPPING_NOT_SUPPORTED = 2005
'    ERROR_CONNECTION_UNAVAIL = 1201&
'    ERROR_CONTROL_ID_NOT_FOUND = 1421&
'    ERROR_COUNTER_TIMEOUT = 1121&
'    ERROR_CRC = 23&
'    ERROR_CURRENT_DIRECTORY = 16&
'    ERROR_DATABASE_DOES_NOT_EXIST = 1065&
'    ERROR_DC_NOT_FOUND = 1425&
'    ERROR_DEPENDENT_SERVICES_RUNNING = 1051&
'    ERROR_DESTROY_OBJECT_OF_OTHER_THREAD = 1435&
'    ERROR_DEV_NOT_EXIST = 55 '  dderror
'    ERROR_DEVICE_ALREADY_REMEMBERED = 1202&
'    ERROR_DEVICE_IN_USE = 2404&
'    ERROR_DEVICE_NOT_PARTITIONED = 1107&
'    ERROR_DIR_NOT_EMPTY = 145&
'    ERROR_DIR_NOT_ROOT = 144&
'    ERROR_DIRECT_ACCESS_HANDLE = 130&
'    ERROR_DIRECTORY = 267&
'    ERROR_DISCARDED = 157&
'    ERROR_DISK_CHANGE = 107&
'    ERROR_DISK_CORRUPT = 1393&
'    ERROR_DISK_FULL = 112&
'    ERROR_DISK_OPERATION_FAILED = 1127&
'    ERROR_DISK_RECALIBRATE_FAILED = 1126&
'    ERROR_DISK_RESET_FAILED = 1128&
'    ERROR_DLL_INIT_FAILED = 1114&
'    ERROR_DOMAIN_EXISTS = 1356&
'    ERROR_DOMAIN_LIMIT_EXCEEDED = 1357&
'    ERROR_DOMAIN_TRUST_INCONSISTENT = 1810&
'    ERROR_DRIVE_LOCKED = 108&
'    ERROR_DUP_DOMAINNAME = 1221&
'    ERROR_DUP_NAME = 52&
'    ERROR_DUPLICATE_SERVICE_NAME = 1078&
'    ERROR_DYNLINK_FROM_INVALID_RING = 196&
'    ERROR_EA_ACCESS_DENIED = 994&
'    ERROR_EA_FILE_CORRUPT = 276&
'    ERROR_EA_LIST_INCONSISTENT = 255&
'    ERROR_EA_TABLE_FULL = 277&
'    ERROR_EAS_DIDNT_FIT = 275&
'    ERROR_EAS_NOT_SUPPORTED = 282&
'    ERROR_END_OF_MEDIA = 1100&
'    ERROR_ENVVAR_NOT_FOUND = 203&
'    ERROR_EOM_OVERFLOW = 1129&
'    ERROR_EVENTLOG_CANT_START = 1501&
'    ERROR_EVENTLOG_FILE_CHANGED = 1503&
'    ERROR_EVENTLOG_FILE_CORRUPT = 1500&
'    ERROR_EXCEPTION_IN_SERVICE = 1064&
'    ERROR_EXCL_SEM_ALREADY_OWNED = 101&
'    ERROR_EXE_MARKED_INVALID = 192&
'    ERROR_EXTENDED_ERROR = 1208&
'    ERROR_FAIL_I24 = 83&
'    ERROR_FAILED_SERVICE_CONTROLLER_CONNECT = 1063&
'    ERROR_FILE_CORRUPT = 1392&
'    ERROR_FILE_EXISTS = 80&
'    ERROR_FILE_INVALID = 1006&
'    ERROR_FILE_NOT_FOUND = 2&
'    ERROR_FILEMARK_DETECTED = 1101&
'    ERROR_FILENAME_EXCED_RANGE = 206&
'    ERROR_FLOPPY_BAD_REGISTERS = 1125&
'    ERROR_FLOPPY_ID_MARK_NOT_FOUND = 1122&
'    ERROR_FLOPPY_UNKNOWN_ERROR = 1124&
'    ERROR_FLOPPY_WRONG_CYLINDER = 1123&
'    ERROR_FULL_BACKUP = 4004
'    ERROR_FULLSCREEN_MODE = 1007&
'    ERROR_GEN_FAILURE = 31&
'    ERROR_GENERIC_NOT_MAPPED = 1360&
'    ERROR_GROUP_EXISTS = 1318&
'    ERROR_HANDLE_DISK_FULL = 39&
'    ERROR_HANDLE_EOF = 38&
'    ERROR_HOOK_NEEDS_HMOD = 1428&
'    ERROR_HOOK_NOT_INSTALLED = 1431&
'    ERROR_HOTKEY_ALREADY_REGISTERED = 1409&
'    ERROR_HOTKEY_NOT_REGISTERED = 1419&
'    ERROR_HWNDS_HAVE_DIFF_PARENT = 1441&
'    ERROR_ILL_FORMED_PASSWORD = 1324&
'    ERROR_INC_BACKUP = 4003
'    ERROR_INFLOOP_IN_RELOC_CHAIN = 202&
'    ERROR_INSUFFICIENT_BUFFER = 122 '  dderror
'    ERROR_INTERNAL_DB_CORRUPTION = 1358&
'    ERROR_INTERNAL_DB_ERROR = 1383&
'    ERROR_INTERNAL_ERROR = 1359&
'    ERROR_INVALID_ACCEL_HANDLE = 1403&
'    ERROR_INVALID_ACCESS = 12&
'    ERROR_INVALID_ACCOUNT_NAME = 1315&
'    ERROR_INVALID_ACL = 1336&
'    ERROR_INVALID_ADDRESS = 487&
'    ERROR_INVALID_AT_INTERRUPT_TIME = 104&
'    ERROR_INVALID_BLOCK = 9&
'    ERROR_INVALID_BLOCK_LENGTH = 1106&
'    ERROR_INVALID_CATEGORY = 117&
'    ERROR_INVALID_COMBOBOX_MESSAGE = 1422&
'    ERROR_INVALID_COMPUTERNAME = 1210&
'    ERROR_INVALID_CURSOR_HANDLE = 1402&
'    ERROR_INVALID_DATA = 13&
'    ERROR_INVALID_DATATYPE = 1804&
'    ERROR_INVALID_DOMAIN_ROLE = 1354&
'    ERROR_INVALID_DOMAIN_STATE = 1353&
'    ERROR_INVALID_DOMAINNAME = 1212&
'    ERROR_INVALID_DRIVE = 15&
'    ERROR_INVALID_DWP_HANDLE = 1405&
'    ERROR_INVALID_EA_HANDLE = 278&
'    ERROR_INVALID_EA_NAME = 254&
'    ERROR_INVALID_EDIT_HEIGHT = 1424&
'    ERROR_INVALID_ENVIRONMENT = 1805&
'    ERROR_INVALID_EVENT_COUNT = 151&
'    ERROR_INVALID_EVENTNAME = 1211&
'    ERROR_INVALID_EXE_SIGNATURE = 191&
'    ERROR_INVALID_FILTER_PROC = 1427&
'    ERROR_INVALID_FLAG_NUMBER = 186&
'    ERROR_INVALID_FLAGS = 1004&
'    ERROR_INVALID_FORM_NAME = 1902&
'    ERROR_INVALID_FORM_SIZE = 1903&
'    ERROR_INVALID_FUNCTION = 1 '  dderror
'    ERROR_INVALID_GROUP_ATTRIBUTES = 1345&
'    ERROR_INVALID_GROUPNAME = 1209&
'    ERROR_INVALID_GW_COMMAND = 1443&
'    ERROR_INVALID_HANDLE = 6&
'    ERROR_INVALID_HOOK_FILTER = 1426&
'    ERROR_INVALID_HOOK_HANDLE = 1404&
'    ERROR_INVALID_ICON_HANDLE = 1414&
'    ERROR_INVALID_ID_AUTHORITY = 1343&
'    ERROR_INVALID_INDEX = 1413&
'    ERROR_INVALID_LB_MESSAGE = 1432&
'    ERROR_INVALID_LEVEL = 124&
'    ERROR_INVALID_LIST_FORMAT = 153&
'    ERROR_INVALID_LOGON_HOURS = 1328&
'    ERROR_INVALID_LOGON_TYPE = 1367&
'    ERROR_INVALID_MEMBER = 1388&
'    ERROR_INVALID_MENU_HANDLE = 1401&
'    ERROR_INVALID_MESSAGE = 1002&
'    ERROR_INVALID_MESSAGEDEST = 1218&
'    ERROR_INVALID_MESSAGENAME = 1217&
'    ERROR_INVALID_MINALLOCSIZE = 195&
'    ERROR_INVALID_MODULETYPE = 190&
'    ERROR_INVALID_MSGBOX_STYLE = 1438&
'    ERROR_INVALID_NAME = 123&
'    ERROR_INVALID_NETNAME = 1214&
'    ERROR_INVALID_ORDINAL = 182&
'    ERROR_INVALID_OWNER = 1307&
'    ERROR_INVALID_PARAMETER = 87 '  dderror
'    ERROR_INVALID_PASSWORD = 86&
'    ERROR_INVALID_PASSWORDNAME = 1216&
'    ERROR_INVALID_PIXEL_FORMAT = 2000
'    ERROR_INVALID_PRIMARY_GROUP = 1308&
'    ERROR_INVALID_PRINTER_COMMAND = 1803&
'    ERROR_INVALID_PRINTER_NAME = 1801&
'    ERROR_INVALID_PRINTER_STATE = 1906&
'    ERROR_INVALID_PRIORITY = 1800&
'    ERROR_INVALID_SCROLLBAR_RANGE = 1448&
'    ERROR_INVALID_SECURITY_DESCR = 1338&
'    ERROR_INVALID_SEGDPL = 198&
'    ERROR_INVALID_SEGMENT_NUMBER = 180&
'    ERROR_INVALID_SEPARATOR_FILE = 1799&
'    ERROR_INVALID_SERVER_STATE = 1352&
'    ERROR_INVALID_SERVICE_ACCOUNT = 1057&
'    ERROR_INVALID_SERVICE_CONTROL = 1052&
'    ERROR_INVALID_SERVICE_LOCK = 1071&
'    ERROR_INVALID_SERVICENAME = 1213&
'    ERROR_INVALID_SHARENAME = 1215&
'    ERROR_INVALID_SHOWWIN_COMMAND = 1449&
'    ERROR_INVALID_SID = 1337&
'    ERROR_INVALID_SIGNAL_NUMBER = 209&
'    ERROR_INVALID_SPI_VALUE = 1439&
'    ERROR_INVALID_STACKSEG = 189&
'    ERROR_INVALID_STARTING_CODESEG = 188&
'    ERROR_INVALID_SUB_AUTHORITY = 1335&
'    ERROR_INVALID_TARGET_HANDLE = 114&
'    ERROR_INVALID_THREAD_ID = 1444&
'    ERROR_INVALID_TIME = 1901&
'    ERROR_INVALID_USER_BUFFER = 1784&
'    ERROR_INVALID_VERIFY_SWITCH = 118&
'    ERROR_INVALID_WINDOW_HANDLE = 1400&
'    ERROR_INVALID_WINDOW_STYLE = 2002
'    ERROR_INVALID_WORKSTATION = 1329&
'    ERROR_IO_DEVICE = 1117&
'    ERROR_IO_INCOMPLETE = 996&
'    ERROR_IO_PENDING = 997 '  dderror
'    ERROR_IOPL_NOT_ENABLED = 197&
'    ERROR_IRQ_BUSY = 1119&
'    ERROR_IS_JOIN_PATH = 147&
'    ERROR_IS_JOIN_TARGET = 133&
'    ERROR_IS_JOINED = 134&
'    ERROR_IS_SUBST_PATH = 146&
'    ERROR_IS_SUBST_TARGET = 149&
'    ERROR_IS_SUBSTED = 135&
'    ERROR_ITERATED_DATA_EXCEEDS_64k = 194&
'    ERROR_JOIN_TO_JOIN = 138&
'    ERROR_JOIN_TO_SUBST = 140&
'    ERROR_JOURNAL_HOOK_SET = 1430&
'    ERROR_KEY_DELETED = 1018&
'    ERROR_KEY_HAS_CHILDREN = 1020&
'    ERROR_LABEL_TOO_LONG = 154&
'    ERROR_LAST_ADMIN = 1322&
'    ERROR_LB_WITHOUT_TABSTOPS = 1434&
'    ERROR_LISTBOX_ID_NOT_FOUND = 1416&
'    ERROR_LM_CROSS_ENCRYPTION_REQUIRED = 1390&
'    ERROR_LOCAL_USER_SESSION_KEY = 1303&
'    ERROR_LOCK_FAILED = 167&
'    ERROR_LOCK_VIOLATION = 33&
'    ERROR_LOCKED = 212&
'    ERROR_LOG_FILE_FULL = 1502&
'    ERROR_LOGON_FAILURE = 1326&
'    ERROR_LOGON_NOT_GRANTED = 1380&
'    ERROR_LOGON_SESSION_COLLISION = 1366&
'    ERROR_LOGON_SESSION_EXISTS = 1363&
'    ERROR_LOGON_TYPE_NOT_GRANTED = 1385&
'    ERROR_LUIDS_EXHAUSTED = 1334&
'    ERROR_MAPPED_ALIGNMENT = 1132&
'    ERROR_MAX_THRDS_REACHED = 164&
'    ERROR_MEDIA_CHANGED = 1110&
'    ERROR_MEMBER_IN_ALIAS = 1378&
'    ERROR_MEMBER_IN_GROUP = 1320&
'    ERROR_MEMBER_NOT_IN_ALIAS = 1377&
'    ERROR_MEMBER_NOT_IN_GROUP = 1321&
'    ERROR_MEMBERS_PRIMARY_GROUP = 1374&
'    ERROR_META_EXPANSION_TOO_LONG = 208&
'    ERROR_METAFILE_NOT_SUPPORTED = 2003
'    ERROR_MOD_NOT_FOUND = 126&
'    ERROR_MORE_DATA = 234 '  dderror
'    ERROR_MORE_WRITES = 1120&
'    ERROR_MR_MID_NOT_FOUND = 317&
'    ERROR_NEGATIVE_SEEK = 131&
'    ERROR_NESTING_NOT_ALLOWED = 215&
'    ERROR_NET_WRITE_FAULT = 88&
'    ERROR_NETLOGON_NOT_STARTED = 1792&
'    ERROR_NETNAME_DELETED = 64&
'    ERROR_NETWORK_ACCESS_DENIED = 65&
'    ERROR_NETWORK_BUSY = 54&
'    ERROR_NO_BROWSER_SERVERS_FOUND = 6118&
'    ERROR_NO_DATA = 232&
'    ERROR_NO_DATA_DETECTED = 1104&
'    ERROR_NO_IMPERSONATION_TOKEN = 1309&
'    ERROR_NO_INHERITANCE = 1391&
'    ERROR_NO_LOG_SPACE = 1019&
'    ERROR_NO_LOGON_SERVERS = 1311&
'    ERROR_NO_MEDIA_IN_DRIVE = 1112&
'    ERROR_NO_MORE_FILES = 18&
'    ERROR_NO_MORE_ITEMS = 259&
'    ERROR_NO_MORE_SEARCH_HANDLES = 113&
'    ERROR_NO_NET_OR_BAD_PATH = 1203&
'    ERROR_NO_NETWORK = 1222&
'    ERROR_NO_PROC_SLOTS = 89&
'    ERROR_NO_QUOTAS_FOR_ACCOUNT = 1302&
'    ERROR_NO_SCROLLBARS = 1447&
'    ERROR_NO_SECURITY_ON_OBJECT = 1350&
'    ERROR_NO_SHUTDOWN_IN_PROGRESS = 1116&
'    ERROR_NO_SIGNAL_SENT = 205&
'    ERROR_NO_SPOOL_SPACE = 62&
'    ERROR_NO_SUCH_ALIAS = 1376&
'    ERROR_NO_SUCH_DOMAIN = 1355&
'    ERROR_NO_SUCH_GROUP = 1319&
'    ERROR_NO_SUCH_LOGON_SESSION = 1312&
'    ERROR_NO_SUCH_MEMBER = 1387&
'    ERROR_NO_SUCH_PACKAGE = 1364&
'    ERROR_NO_SUCH_PRIVILEGE = 1313&
'    ERROR_NO_SUCH_USER = 1317&
'    ERROR_NO_SYSTEM_MENU = 1437&
'    ERROR_NO_TOKEN = 1008&
'    ERROR_NO_TRUST_LSA_SECRET = 1786&
'    ERROR_NO_TRUST_SAM_ACCOUNT = 1787&
'    ERROR_NO_UNICODE_TRANSLATION = 1113&
'    ERROR_NO_USER_SESSION_KEY = 1394&
'    ERROR_NO_VOLUME_LABEL = 125&
'    ERROR_NO_WILDCARD_CHARACTERS = 1417&
'    ERROR_NOACCESS = 998&
'    ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT = 1807&
'    ERROR_NOLOGON_SERVER_TRUST_ACCOUNT = 1809&
'    ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT = 1808&
'    ERROR_NON_MDICHILD_WINDOW = 1445&
'    ERROR_NONE_MAPPED = 1332&
'    ERROR_NOT_ALL_ASSIGNED = 1300&
'    ERROR_NOT_CHILD_WINDOW = 1442&
'    ERROR_NOT_CONNECTED = 2250&
'    ERROR_NOT_CONTAINER = 1207&
'    ERROR_NOT_DOS_DISK = 26&
'    ERROR_NOT_ENOUGH_MEMORY = 8 '  dderror
'    ERROR_NOT_ENOUGH_QUOTA = 1816&
'    ERROR_NOT_ENOUGH_SERVER_MEMORY = 1130&
'    ERROR_NOT_JOINED = 136&
'    ERROR_NOT_LOCKED = 158&
'    ERROR_NOT_LOGON_PROCESS = 1362&
'    ERROR_NOT_OWNER = 288&
'    ERROR_NOT_READY = 21&
'    ERROR_NOT_REGISTRY_FILE = 1017&
'    ERROR_NOT_SAME_DEVICE = 17&
'    ERROR_NOT_SUBSTED = 137&
'    ERROR_NOT_SUPPORTED = 50&
'    ERROR_NOTIFY_ENUM_DIR = 1022&
'    ERROR_NT_CROSS_ENCRYPTION_REQUIRED = 1386&
'    ERROR_NULL_LM_PASSWORD = 1304&
'    ERROR_OPEN_FAILED = 110&
'    ERROR_OPEN_FILES = 2401&
'    ERROR_OPERATION_ABORTED = 995&
'    ERROR_OUT_OF_PAPER = 28&
'    ERROR_OUT_OF_STRUCTURES = 84&
'    ERROR_OUTOFMEMORY = 14&
'    ERROR_PARTITION_FAILURE = 1105&
'    ERROR_PASSWORD_EXPIRED = 1330&
'    ERROR_PASSWORD_RESTRICTION = 1325&
'    ERROR_PATH_BUSY = 148&
'    ERROR_PATH_NOT_FOUND = 3&
'    ERROR_PIPE_BUSY = 231&
'    ERROR_PIPE_CONNECTED = 535&
'    ERROR_PIPE_LISTENING = 536&
'    ERROR_PIPE_NOT_CONNECTED = 233&
'    ERROR_POPUP_ALREADY_ACTIVE = 1446&
'    ERROR_POSSIBLE_DEADLOCK = 1131&
'    ERROR_PRINT_CANCELLED = 63&
'    ERROR_PRINT_MONITOR_ALREADY_INSTALLED = 3006
'    ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED = 3005
'    ERROR_PRINTER_ALREADY_EXISTS = 1802&
'    ERROR_PRINTER_DELETED = 1905&
'    ERROR_PRINTER_DRIVER_ALREADY_INSTALLED = 1795&
'    ERROR_PRINTER_DRIVER_IN_USE = 3001
'    ERROR_PRINTQ_FULL = 61&
'    ERROR_PRIVATE_DIALOG_INDEX = 1415&
'    ERROR_PRIVILEGE_NOT_HELD = 1314&
'    ERROR_PROC_NOT_FOUND = 127&
'    ERROR_PROCESS_ABORTED = 1067&
'    ERROR_PUBLIC_ONLY_HOOK = 1429&
'    ERROR_READ_FAULT = 30&
'    ERROR_REC_NON_EXISTENT = 4005
'    ERROR_REDIR_PAUSED = 72&
'    ERROR_REDIRECTOR_HAS_OPEN_HANDLES = 1794&
'    ERROR_REGISTRY_CORRUPT = 1015&
'    ERROR_REGISTRY_IO_FAILED = 1016&
'    ERROR_REGISTRY_RECOVERED = 1014&
'    ERROR_RELOC_CHAIN_XEEDS_SEGLIM = 201&
'    ERROR_REM_NOT_LIST = 51&
'    ERROR_REMOTE_SESSION_LIMIT_EXCEEDED = 1220&
'    ERROR_REQ_NOT_ACCEP = 71&
'    ERROR_RESOURCE_DATA_NOT_FOUND = 1812&
'    ERROR_RESOURCE_LANG_NOT_FOUND = 1815&
'    ERROR_RESOURCE_NAME_NOT_FOUND = 1814&
'    ERROR_RESOURCE_TYPE_NOT_FOUND = 1813&
'    ERROR_REVISION_MISMATCH = 1306&
'    ERROR_RING2_STACK_IN_USE = 207&
'    ERROR_RING2SEG_MUST_BE_MOVABLE = 200&
'    ERROR_RPL_NOT_ALLOWED = 4006
'    ERROR_RXACT_COMMIT_FAILURE = 1370&
'    ERROR_RXACT_INVALID_STATE = 1369&
'    ERROR_SAME_DRIVE = 143&
'    ERROR_SCREEN_ALREADY_LOCKED = 1440&
'    ERROR_SECRET_TOO_LONG = 1382&
'    ERROR_SECTOR_NOT_FOUND = 27&
'    ERROR_SEEK = 25&
'    ERROR_SEEK_ON_DEVICE = 132&
'    ERROR_SEM_IS_SET = 102&
'    ERROR_SEM_NOT_FOUND = 187&
'    ERROR_SEM_OWNER_DIED = 105&
'    ERROR_SEM_TIMEOUT = 121&
'    ERROR_SEM_USER_LIMIT = 106&
'    ERROR_SERIAL_NO_DEVICE = 1118&
'    ERROR_SERVER_DISABLED = 1341&
'    ERROR_SERVER_HAS_OPEN_HANDLES = 1811&
'    ERROR_SERVER_NOT_DISABLED = 1342&
'    ERROR_SERVICE_ALREADY_RUNNING = 1056&
'    ERROR_SERVICE_CANNOT_ACCEPT_CTRL = 1061&
'    ERROR_SERVICE_DATABASE_LOCKED = 1055&
'    ERROR_SERVICE_DEPENDENCY_DELETED = 1075&
'    ERROR_SERVICE_DEPENDENCY_FAIL = 1068&
'    ERROR_SERVICE_DISABLED = 1058&
'    ERROR_SERVICE_DOES_NOT_EXIST = 1060&
'    ERROR_SERVICE_EXISTS = 1073&
'    ERROR_SERVICE_LOGON_FAILED = 1069&
'    ERROR_SERVICE_MARKED_FOR_DELETE = 1072&
'    ERROR_SERVICE_NEVER_STARTED = 1077&
'    ERROR_SERVICE_NO_THREAD = 1054&
'    ERROR_SERVICE_NOT_ACTIVE = 1062&
'    ERROR_SERVICE_REQUEST_TIMEOUT = 1053&
'    ERROR_SERVICE_SPECIFIC_ERROR = 1066&
'    ERROR_SERVICE_START_HANG = 1070&
'    ERROR_SESSION_CREDENTIAL_CONFLICT = 1219&
'    ERROR_SETCOUNT_ON_BAD_LB = 1433&
'    ERROR_SETMARK_DETECTED = 1103&
'    ERROR_SEVERITY_ERROR = &HC0000000
'    ERROR_SEVERITY_INFORMATIONAL = &H40000000
'    ERROR_SEVERITY_SUCCESS = &H0
'    ERROR_SEVERITY_WARNING = &H80000000
'    ERROR_SHARING_BUFFER_EXCEEDED = 36&
'    ERROR_SHARING_PAUSED = 70&
'    ERROR_SHARING_VIOLATION = 32&
'    ERROR_SHUTDOWN_IN_PROGRESS = 1115&
'    ERROR_SIGNAL_PENDING = 162&
'    ERROR_SIGNAL_REFUSED = 156&
'    ERROR_SOME_NOT_MAPPED = 1301&
'    ERROR_SPECIAL_ACCOUNT = 1371&
'    ERROR_SPECIAL_GROUP = 1372&
'    ERROR_SPECIAL_USER = 1373&
'    ERROR_SPL_NO_ADDJOB = 3004
'    ERROR_SPL_NO_STARTDOC = 3003
'    ERROR_SPOOL_FILE_NOT_FOUND = 3002
'    ERROR_STACK_OVERFLOW = 1001&
'    ERROR_STATIC_INIT = 4002
'    ERROR_SUBST_TO_JOIN = 141&
'    ERROR_SUBST_TO_SUBST = 139&
'    ERROR_SUCCESS = 0&
'    ERROR_SWAPERROR = 999&
'    ERROR_SYSTEM_TRACE = 150&
'    ERROR_THREAD_1_INACTIVE = 210&
'    ERROR_TLW_WITH_WSCHILD = 1406&
'    ERROR_TOKEN_ALREADY_IN_USE = 1375&
'    ERROR_TOO_MANY_CMDS = 56&
'    ERROR_TOO_MANY_CONTEXT_IDS = 1384&
'    ERROR_TOO_MANY_LUIDS_REQUESTED = 1333&
'    ERROR_TOO_MANY_MODULES = 214&
'    ERROR_TOO_MANY_MUXWAITERS = 152&
'    ERROR_TOO_MANY_NAMES = 68&
'    ERROR_TOO_MANY_OPEN_FILES = 4&
'    ERROR_TOO_MANY_POSTS = 298&
'    ERROR_TOO_MANY_SECRETS = 1381&
'    ERROR_TOO_MANY_SEM_REQUESTS = 103&
'    ERROR_TOO_MANY_SEMAPHORES = 100&
'    ERROR_TOO_MANY_SESS = 69&
'    ERROR_TOO_MANY_SIDS = 1389&
'    ERROR_TOO_MANY_TCBS = 155&
'    ERROR_TRANSFORM_NOT_SUPPORTED = 2004
'    ERROR_TRUST_FAILURE = 1790&
'    ERROR_TRUSTED_DOMAIN_FAILURE = 1788&
'    ERROR_TRUSTED_RELATIONSHIP_FAILURE = 1789&
'    ERROR_UNABLE_TO_LOCK_MEDIA = 1108&
'    ERROR_UNABLE_TO_UNLOAD_MEDIA = 1109&
'    ERROR_UNEXP_NET_ERR = 59&
'    ERROR_UNKNOWN_PORT = 1796&
'    ERROR_UNKNOWN_PRINT_MONITOR = 3000
'    ERROR_UNKNOWN_PRINTER_DRIVER = 1797&
'    ERROR_UNKNOWN_PRINTPROCESSOR = 1798&
'    ERROR_UNKNOWN_REVISION = 1305&
'    ERROR_UNRECOGNIZED_MEDIA = 1785&
'    ERROR_UNRECOGNIZED_VOLUME = 1005&
'    ERROR_USER_EXISTS = 1316&
'    ERROR_VC_DISCONNECTED = 240&
'    ERROR_WAIT_NO_CHILDREN = 128&
'    ERROR_WINDOW_NOT_COMBOBOX = 1423&
'    ERROR_WINDOW_NOT_DIALOG = 1420&
'    ERROR_WINDOW_OF_OTHER_THREAD = 1408&
'    ERROR_WINS_INTERNAL = 4000
'    ERROR_WRITE_FAULT = 29&
'    ERROR_WRITE_PROTECT = 19&
'    ERROR_WRONG_DISK = 34&
'    ERROR_WRONG_PASSWORD = 1323&
End Enum

Public Enum enumFileAttributes
    efaARCHIVE = &H20
    efaCOMPRESSED = &H800
    efaDIRECTORY = &H10
    efaHIDDEN = &H2
    efaNORMAL = &H80
    efaREADONLY = &H1
    efaSYSTEM = &H4
    efaTEMPORARY = &H100
End Enum


Public Enum enumControlProperties
    cpMultiLine = 2 ^ 0
    cpWordWrap = 2 ^ 1
    
End Enum

Public Enum enumQuoteTypes
    qtSingleTick = 2 ^ 0
    qtDoubleQuote = 2 ^ 1
End Enum

Public Enum enumDelimiters
    edComma = 44
    edTilde = 126
    edSpace = 32
    edDash = 45
    edPipe = 124
End Enum


'------------------------------------------------------
' List of different styles of keyboard entry allowed.
' Goes with the function ctlKeyPress()
Public Enum enumKeyPressAllowTypes
    OnlyNumbers = 2 ^ 0
    Uppercase = 2 ^ 1
    NoSpaces = 2 ^ 2
    NoSingleQuotes = 2 ^ 3
    NoDoubleQuotes = 2 ^ 4
    AllowDecimal = 2 ^ 5
    AllowNegative = 2 ^ 6
    OnlyDates = 2 ^ 7
    OnlyTimes = 2 ^ 8
    OnlyLetters = 2 ^ 9
    AllowSpaces = 2 ^ 10
    AllowStars = 2 ^ 11
    AllowPounds = 2 ^ 12
    
    OnlyMoney = OnlyNumbers + AllowDecimal + AllowNegative
    
End Enum



Public Enum enumLockWindowUpdates
    elwLOCK = 1
    elwUNLOCK = 2
End Enum

Public Enum enumLanguageIDs
    LANG__DEFAULT = &H0
    LANG_BULGARIAN = &H2
    LANG_CHINESE = &H4
    LANG_CROATIAN = &H1A
    LANG_CZECH = &H5
    LANG_DANISH = &H6
    LANG_DUTCH = &H13
    LANG_ENGLISH = &H9
    LANG_FINNISH = &HB
    LANG_FRENCH = &HC
    LANG_GERMAN = &H7
    LANG_GREEK = &H8
    LANG_HUNGARIAN = &HE
    LANG_ICELANDIC = &HF
    LANG_ITALIAN = &H10
    LANG_JAPANESE = &H11
    LANG_KOREAN = &H12
    LANG_NEUTRAL = &H0
    LANG_NORWEGIAN = &H14
    LANG_POLISH = &H15
    LANG_PORTUGUESE = &H16
    LANG_ROMANIAN = &H18
    LANG_RUSSIAN = &H19
    LANG_SLOVAK = &H1B
    LANG_SLOVENIAN = &H24
    LANG_SPANISH = &HA
    LANG_SWEDISH = &H1D
    LANG_TURKISH = &H1F
End Enum

Public Enum enumFormatMessageFlags
    FORMAT_MESSAGE_ALLOCATE_BUFFER = &H100
    FORMAT_MESSAGE_ARGUMENT_ARRAY = &H2000
    FORMAT_MESSAGE_FROM_HMODULE = &H800
    FORMAT_MESSAGE_FROM_STRING = &H400
    FORMAT_MESSAGE_FROM_SYSTEM = &H1000
    FORMAT_MESSAGE_IGNORE_INSERTS = &H200
    FORMAT_MESSAGE_MAX_WIDTH_MASK = &HFF
End Enum

Public Enum enumGetWindowLongOptions
    GWL_EXSTYLE = (-20)
    GWL_HINSTANCE = (-6)
    GWL_HWNDPARENT = (-8)
    GWL_ID = (-12)
    GWL_STYLE = (-16)
    GWL_USERDATA = (-21)
    GWL_WNDPROC = (-4)
End Enum

Public Enum enumGetWindowOptions
    GW_HWNDFIRST = 0
    GW_HWNDLAST = 1
    GW_HWNDNEXT = 2
    GW_HWNDPREV = 3
    GW_OWNER = 4
    GW_CHILD = 5
    GW_MAX = GW_CHILD
End Enum

Public Enum enumChildWindows
    ecwMDIforms = 1
    ecwALL = ecwMDIforms
End Enum

Public Enum enumWindowStyles
    WS_BORDER = &H800000
    WS_CAPTION = &HC00000
    WS_CHILD = &H40000000
    WS_CLIPCHILDREN = &H2000000
    WS_CLIPSIBLINGS = &H4000000
    WS_DISABLED = &H8000000
    WS_DLGFRAME = &H400000
    WS_EX_ACCEPTFILES = &H10&
    WS_EX_DLGMODALFRAME = &H1&
    WS_EX_NOPARENTNOTIFY = &H4&
    WS_EX_TOPMOST = &H8&
    WS_EX_TRANSPARENT = &H20&
    WS_GROUP = &H20000
    WS_HSCROLL = &H100000
    WS_MAXIMIZE = &H1000000
    WS_MAXIMIZEBOX = &H10000
    WS_MINIMIZE = &H20000000
    WS_MINIMIZEBOX = &H20000
    WS_OVERLAPPED = &H0&
    WS_POPUP = &H80000000
    WS_SYSMENU = &H80000
    WS_TABSTOP = &H10000
    WS_THICKFRAME = &H40000
    WS_VISIBLE = &H10000000
    WS_VSCROLL = &H200000
    WS_TILED = WS_OVERLAPPED
    WS_CHILDWINDOW = (WS_CHILD)
    WS_ICONIC = WS_MINIMIZE
    WS_SIZEBOX = WS_THICKFRAME
    WS_POPUPWINDOW = (WS_POPUP Or WS_BORDER Or WS_SYSMENU)
    WS_TILEDWINDOW = WS_OVERLAPPED
    WS_OVERLAPPEDWINDOW = (WS_OVERLAPPED Or WS_CAPTION Or WS_SYSMENU Or WS_THICKFRAME Or WS_MINIMIZEBOX Or WS_MAXIMIZEBOX)
End Enum

Public Enum enumWindowButtons
    eWS_VSCROLL = WS_VSCROLL
    eWS_CAPTION = WS_CAPTION
    eWS_MAXIMIZEBOX = WS_MAXIMIZEBOX
    eWS_MINIMIZEBOX = WS_MINIMIZEBOX
    eWS_SIZEBOX = WS_SIZEBOX
    eWS_SYSMENU = WS_SYSMENU
    eWS_ALL = WS_MAXIMIZEBOX + WS_MINIMIZEBOX + WS_SIZEBOX + WS_SYSMENU + WS_CAPTION
    eWS_TITLEBAR = WS_MAXIMIZEBOX + WS_MINIMIZEBOX + WS_SYSMENU + WS_CAPTION
End Enum

Public Enum enumClassStyles
    CS_BYTEALIGNCLIENT = &H1000
    CS_BYTEALIGNWINDOW = &H2000
    CS_CLASSDC = &H40
    CS_DBLCLKS = &H8
    CS_HREDRAW = &H2
    CS_INSERTCHAR = &H2000
    CS_KEYCVTWINDOW = &H4
    CS_NOCLOSE = &H200
    CS_NOKEYCVT = &H100
    CS_NOMOVECARET = &H4000
    CS_OWNDC = &H20
    CS_PARENTDC = &H80
    CS_PUBLICCLASS = &H4000
    CS_SAVEBITS = &H800
    CS_VREDRAW = &H1
End Enum

Public Enum enumAddRecentDocuments
    SHARD_PIDL = &H1&
    SHARD_PATH = &H2&
End Enum

Public Enum enumShellWindows
    SW_ERASE = &H4
    SW_HIDE = 0
    SW_INVALIDATE = &H2
    SW_MAX = 10
    SW_MAXIMIZE = 3
    SW_MINIMIZE = 6
    SW_NORMAL = 1
    SW_OTHERUNZOOM = 4
    SW_OTHERZOOM = 2
    SW_PARENTCLOSING = 1
    SW_PARENTOPENING = 3
    SW_RESTORE = 9
    SW_SCROLLCHILDREN = &H1
    SW_SHOW = 5
    SW_SHOWDEFAULT = 10
    SW_SHOWMAXIMIZED = 3
    SW_SHOWMINIMIZED = 2
    SW_SHOWMINNOACTIVE = 7
    SW_SHOWNA = 8
    SW_SHOWNOACTIVATE = 4
    SW_SHOWRESTORE = 5
    SW_SHOWNORMAL = 1
End Enum

Public Enum enumShowWindow
    esw_SHOWDEFAULT = SW_SHOWDEFAULT
    esw_SHOWMAXIMIZED = SW_SHOWMAXIMIZED
    esw_SHOWMINIMIZED = SW_SHOWMINIMIZED
    esw_SHOWMINNOACTIVE = SW_SHOWMINNOACTIVE
    esw_SHOWNA = SW_SHOWNA
    esw_SHOWNOACTIVATE = SW_SHOWNOACTIVATE
    esw_SHOWRESTORE = SW_SHOWRESTORE
    esw_SHOWNORMAL = SW_SHOWNORMAL
    
End Enum

Public Enum enumShellExecuteErrors
    SE_ERR_FNF = 2&
    SE_ERR_PNF = 3&
    SE_ERR_ACCESSDENIED = 5&
    SE_ERR_OOM = 8&
    SE_ERR_DLLNOTFOUND = 32&
    SE_ERR_SHARE = 26&
    SE_ERR_ASSOCINCOMPLETE = 27&
    SE_ERR_DDETIMEOUT = 28&
    SE_ERR_DDEFAIL = 29&
    SE_ERR_DDEBUSY = 30&
    SE_ERR_NOASSOC = 31&
    SE_ERROR_BAD_FORMAT = ERROR_BAD_FORMAT
End Enum


Public Enum enumGetFolderPath
    SHGFP_TYPE_CURRENT = &H0             'current value for user, verify it exists
    SHGFP_TYPE_DEFAULT = &H1
End Enum

Public Enum enumShellFolders        ' Shell Folder Path Constants...
    CSIDL_DESKTOP = &H0                 '{desktop}
    CSIDL_INTERNET = &H1                'Internet Explorer (icon on desktop)
    CSIDL_PROGRAMS = &H2                'Start Menu\Programs
    CSIDL_CONTROLS = &H3                'My Computer\Control Panel
    CSIDL_PRINTERS = &H4                'My Computer\Printers
    CSIDL_PERSONAL = &H5                'My Documents
    CSIDL_FAVORITES = &H6               '{user name}\Favorites
    CSIDL_STARTUP = &H7                 'Start Menu\Programs\Startup
    CSIDL_RECENT = &H8                  '{user name}\Recent
    CSIDL_SENDTO = &H9                  '{user name}\SendTo
    CSIDL_BITBUCKET = &HA               '{desktop}\Recycle Bin
    CSIDL_STARTMENU = &HB               '{user name}\Start Menu
    CSIDL_DESKTOPDIRECTORY = &H10       '{user name}\Desktop
    CSIDL_DRIVES = &H11                 'My Computer
    CSIDL_NETWORK = &H12                'Network Neighborhood
    CSIDL_NETHOOD = &H13                '{user name}\nethood
    CSIDL_FONTS = &H14                  'windows\fonts
    CSIDL_TEMPLATES = &H15
    CSIDL_COMMON_STARTMENU = &H16       'All Users\Start Menu
    CSIDL_COMMON_PROGRAMS = &H17        'All Users\Programs
    CSIDL_COMMON_STARTUP = &H18         'All Users\Startup
    CSIDL_COMMON_DESKTOPDIRECTORY = &H19 'All Users\Desktop
    CSIDL_APPDATA = &H1A                '{user name}\Application Data
    CSIDL_PRINTHOOD = &H1B              '{user name}\PrintHood
    CSIDL_LOCAL_APPDATA = &H1C          '{user name}\Local Settings\Application Data (non roaming)
    CSIDL_ALTSTARTUP = &H1D             'non localized startup
    CSIDL_COMMON_ALTSTARTUP = &H1E      'non localized common startup
    CSIDL_COMMON_FAVORITES = &H1F
    CSIDL_INTERNET_CACHE = &H20
    CSIDL_COOKIES = &H21
    CSIDL_HISTORY = &H22
    CSIDL_COMMON_APPDATA = &H23          'All Users\Application Data
    CSIDL_WINDOWS = &H24                 'GetWindowsDirectory()
    CSIDL_SYSTEM = &H25                  'GetSystemDirectory()
    CSIDL_PROGRAM_FILES = &H26           'C:\Program Files
    CSIDL_MYPICTURES = &H27              'C:\Program Files\My Pictures
    CSIDL_PROFILE = &H28                 'USERPROFILE
    CSIDL_SYSTEMX86 = &H29               'x86 system directory on RISC
    CSIDL_PROGRAM_FILESX86 = &H2A        'x86 C:\Program Files on RISC
    CSIDL_PROGRAM_FILES_COMMON = &H2B    'C:\Program Files\Common
    CSIDL_PROGRAM_FILES_COMMONX86 = &H2C 'x86 Program Files\Common on RISC
    CSIDL_COMMON_TEMPLATES = &H2D        'All Users\Templates
    CSIDL_COMMON_DOCUMENTS = &H2E        'All Users\Documents
    CSIDL_COMMON_ADMINTOOLS = &H2F       'All Users\Start Menu\Programs\Administrative Tools
    CSIDL_ADMINTOOLS = &H30              '{user name}\Start Menu\Programs\Administrative Tools

    CSIDL_FLAG_CREATE = &H8000           'combine with CSIDL_ value to force create on SHGetSpecialFolderLocation()
    CSIDL_FLAG_DONT_VERIFY = &H4000      'combine with CSIDL_ value to force create on SHGetSpecialFolderLocation()
    CSIDL_FLAG_MASK = &HFF00             'mask for all possible flag values
End Enum

Public Enum enumSysMenuCommands
    SC_SIZE = &HF000&
    SC_MOVE = &HF010&
    SC_MINIMIZE = &HF020&
    SC_MAXIMIZE = &HF030&
    SC_NEXTWINDOW = &HF040&
    SC_PREVWINDOW = &HF050&
    SC_CLOSE = &HF060&
    SC_VSCROLL = &HF070&
    SC_HSCROLL = &HF080&
    SC_MOUSEMENU = &HF090&
    SC_KEYMENU = &HF100&
    SC_ARRANGE = &HF110&
    SC_RESTORE = &HF120&
    SC_TASKLIST = &HF130&
    SC_SCREENSAVE = &HF140&
    SC_HOTKEY = &HF150&
End Enum

Public Enum enumMenuFlags
    MF_BYCOMMAND = &H0&
    MF_BYPOSITION = &H400&
End Enum

Public Enum enumVersionPlatforms
    VER_PLATFORM_WIN32_NT = 2
    VER_PLATFORM_WIN32_WINDOWS = 1
    VER_PLATFORM_WIN32s = 0
End Enum

Public Enum enumPossibleProperties
    ppLocked = 1
    ppReadOnly = 2
    ppEnabled = 3
    ppTag = 4
End Enum







'##############################################
'                   TYPES
'##############################################




Public Type COLORMAP
    from As Long
    to As Long
End Type

Public Type twoCOLORMAPs
    from1 As Long
    to1 As Long
    from2 As Long
    to2 As Long
End Type

Public Type threeCOLORMAPs
    from1 As Long
    to1 As Long
    from2 As Long
    to2 As Long
    from3 As Long
    to3 As Long
End Type



Public Type PictDesc
    Size As Long
    Type As Long
    hBmp As Long
    hPal As Long
    Reserved As Long
End Type

Public Type IID
    Data1 As Long
    Data2 As Integer
    Data3 As Integer
    Data4(7) As Byte
End Type



Public Type DRAWTEXTPARAMS
    cbSize As Long
    iTabLength As Long
    iLeftMargin As Long
    iRightMargin As Long
    uiLengthDrawn As Long
End Type



Public Type SHFILEOPSTRUCT
    hwnd      As Long
    wFunc     As enumFileOps
    pFrom     As String
    pTo       As String
    fFlags    As Integer
    fAborted  As Boolean
    hNameMaps As Long
    sProgress As String
End Type






Public Type BrowseInfo
    hWndOwner      As Long
    pIDLRoot       As Long
    pszDisplayName As Long
    lpszTitle      As Long
    ulFlags        As enumBrowseForFlags
    lpfnCallback   As Long
    lParam         As Long
    iImage         As Long
End Type




Public Type FILETIME
        dwLowDateTime As Long
        dwHighDateTime As Long
End Type

Public Type WIN32_FILE_ATTRIBUTE_DATA
    dwFileAtrributes As Long
    ftCreationTime As FILETIME
    ftLastAccessTime As FILETIME
    ftLastWriteTime As FILETIME
    nFileSizeHigh As Long
    nFileSizeLow As Long
End Type

Public Type BY_HANDLE_FILE_INFORMATION
    dwFileAttributes As Long
    ftCreationTime As FILETIME
    ftLastAccessTime As FILETIME
    ftLastWriteTime As FILETIME
    dwVolumeSerialNumber As Long
    nFileSizeHigh As Long
    nFileSizeLow As Long
    nNumberOfLinks As Long
    nFileIndexHigh As Long
    nFileIndexLow As Long
End Type



Public Type typeWNDClassEx
    cbSize As Long
    Style As Long
    lpfnwndproc As Long
    cbClsextra As Long
    cbWndExtra As Long
    hInstance As Long
    hIcon As Long
    hCursor As Long
    hbrBackground As Long
    lpszMenuName As String
    lpszClassName As String
    hIconSm As Long
End Type

Public Type SECURITY_ATTRIBUTES
    nLength As Long
    lpSecurityDescriptor As Long
    bInheritHandle As Long
End Type

Public Type Rect
    Left As Long
    Top As Long
    Right As Long
    Bottom As Long
End Type

Public Type typeOSVERSIONINFO
    dwOSVersionInfoSize As Long
    dwMajorVersion As Long
    dwMinorVersion As Long
    dwBuildNumber As Long
    dwPlatformId As enumVersionPlatforms
    szCSDVersion As String * 128      '  Maintenance string for PSS usage
End Type

Public Type typeOSVERSIONINFOEX
    dwOSVersionInfoSize As Long
    dwMajorVersion As Long
    dwMinorVersion As Long
    dwBuildNumber As Long
    dwPlatformId As enumVersionPlatforms
    szCSDVersion As String * 128      '  Maintenance string for PSS usage
    wServicePackMajor As Integer
    wServicePackMinor As Integer
    wSuiteMask As Integer
    wProductType As Byte
    wReserved As Byte
End Type

Public Type typeBITMAP
    bmType As Long
    bmWidth As Long
    bmHeight As Long
    bmWidthBytes As Long
    bmPlanes As Integer
    bmBitsPixel As Integer
    bmBits As Long
End Type

Public Type COORD
    X As Integer
    Y As Integer
End Type

Public Type POINTAPI
    X As Long
    Y As Long
End Type

Public Type MOUSE_EVENT_RECORD
    dwMousePosition As COORD
    dwButtonState As Long
    dwControlKeyState As Long
    dwEventFlags As Long
End Type

Public Type WINDOWPLACEMENT
        Length As Long
        Flags As Long
        ShowCmd As enumShowWindow
        ptMinPosition As POINTAPI
        ptMaxPosition As POINTAPI
        rcNormalPosition As Rect
End Type

Public Type typeKeyState
    Pressed As Boolean
    Toggled As Boolean
End Type

Public Type TwoBytes
    LoByte As Byte
    HiByte As Byte
End Type

Public Type FourBytes
    LoByte As Byte
    MidLoByte As Byte
    MidHiByte As Byte
    HiByte As Byte
End Type

Public Type OneWord
    Word As Integer
End Type

Public Type TwoWords
    LoWord As Integer
    HiWord As Integer
End Type

Public Type OneDWord
    dWord As Long
End Type

Public Type TwoDWords
    LoDWord As Long
    HiDWord As Long
End Type

Public Type OneQWord
    QWord As Double
End Type

' A simple little data structure that can be used as an array or a collection.
Public Type typeTagData
    Name As String
    Value As String
    Deleted As Boolean
End Type

Public Type typeCOORDS
    Left As Long
    Top As Long
    Width As Long
    Height As Long
End Type

Public Type SYSTEMTIME
    wYear As Integer
    wMonth As Integer
    wDayOfWeek As Integer
    wDay As Integer
    wHour As Integer
    wMinute As Integer
    wSecond As Integer
    wMilliseconds As Integer
End Type

Public Type OFSTRUCT
        cBytes As Byte
        fFixedDisk As Byte
        nErrCode As Integer
        Reserved1 As Integer
        Reserved2 As Integer
        szPathName(OFS_MAXPATHNAME) As Byte
End Type

Public Type WIN32_FIND_DATA
    dwFileAttributes As Long
    ftCreationTime As FILETIME
    ftLastAccessTime As FILETIME
    ftLastWriteTime As FILETIME
    nFileSizeHigh As Long
    nFileSizeLow As Long
    dwReserved0 As Long
    dwReserved1 As Long
    cFileName As String * MAX_PATH
    cAlternate As String * 14
End Type


Public Type typeTagObject
    Tag As String
End Type

Public Type APPBARDATA
        cbSize As Long
        hwnd As Long
        uCallbackMessage As Long
        uEdge As Long
        rc As Rect
        lParam As Long '  message specific
End Type


Public Type typeAppBar
    rs As Rect
    eState As enumAppBarStates
    eEdge As enumAppBarEdges
    
End Type

Public Type GUID
    GUID1 As Long
    GUID2 As Integer
    GUID3 As Integer
    GUID4(0 To 7) As Byte
End Type

Public Type typeVolumeInformation
    sRootPathName As String
    sVolumeName As String
    lVolumeSerialNo As Long
    lMaximumComponentLength As Long
    lFileSystemFlags As Long
    sFileSystemName As String
End Type

Public Type ACL
    AclRevision As Byte
    Sbz1 As Byte
    AclSize As Integer
    AceCount As Integer
    Sbz2 As Integer
End Type


Public Type SECURITY_DESCRIPTOR
    Revision As Byte
    Sbz1 As Byte
    Control As Long
    Owner As Long
    Group As Long
    Sacl As ACL
    Dacl As ACL
End Type


'##############################################
'                 DECLARES
'##############################################
Public Declare Sub CopyMemory _
                            Lib "kernel32" _
                            Alias "RtlMoveMemory" ( _
                        Destination As Any, _
                        Source As Any, _
                        ByVal Length As Long)


Public Declare Function SetFilePointer _
                            Lib "kernel32" ( _
                        ByVal hFile As Long, _
                        ByVal lDistanceToMove As Long, _
                        lpDistanceToMoveHigh As Long, _
                        ByVal dwMoveMethod As Long) _
                    As Long

Public Declare Function SetEndOfFile _
                            Lib "kernel32" ( _
                        ByVal hFile As Long) _
                    As Long

Public Declare Function CloseHandle _
                            Lib "kernel32" ( _
                        ByVal hObject As Long) _
                    As Long


Public Declare Function FileTimeToSystemTime _
                            Lib "kernel32" ( _
                        lpFileTime As FILETIME, _
                        lpSystemTime As SYSTEMTIME) _
                    As Long

Public Declare Function FindFirstFile _
                            Lib "kernel32" _
                            Alias "FindFirstFileA" ( _
                        ByVal lpFileName As String, _
                        lpFindFileData As WIN32_FIND_DATA) _
                    As Long
Public Declare Function FindNextFile _
                            Lib "kernel32" _
                            Alias "FindNextFileA" ( _
                        ByVal hFindFile As Long, _
                        lpFindFileData As WIN32_FIND_DATA) _
                    As Long

Public Declare Function GetLogicalDrives _
                            Lib "kernel32" () _
                    As Long
Public Declare Function GetLogicalDriveStrings _
                            Lib "kernel32" _
                            Alias "GetLogicalDriveStringsA" ( _
                        ByVal nBufferLength As Long, _
                        ByVal lpBuffer As String) _
                    As Long

Public Declare Function GetFileAttributes _
                            Lib "kernel32" _
                            Alias "GetFileAttributesA" ( _
                        ByVal lpFileName As String) _
                    As enumFileAttributes
Public Declare Function OpenFile _
                            Lib "kernel32" ( _
                        ByVal lpFileName As String, _
                        lpReOpenBuff As OFSTRUCT, _
                        ByVal wStyle As Long) _
                    As Long

Public Declare Function GetFileInformationByHandle _
                            Lib "kernel32" ( _
                        ByVal hFile As Long, _
                        lpFileInformation As BY_HANDLE_FILE_INFORMATION) _
                    As Long

Public Declare Function GetExpandedName _
                            Lib "lz32.dll" _
                            Alias "GetExpandedNameA" ( _
                        ByVal lpszSource As String, _
                        ByVal lpszBuffer As String) _
                    As Long

Public Declare Function SetFileAttributes _
                            Lib "kernel32" _
                            Alias "SetFileAttributesA" ( _
                        ByVal lpFileName As String, _
                        ByVal dwFileAttributes As Long) _
                    As Long

Public Declare Function GetFileSize _
                            Lib "kernel32" ( _
                        ByVal hFile As Long, _
                        lpFileSizeHigh As Long) _
                    As Long

Public Declare Function GetShortPathName _
                            Lib "kernel32" _
                            Alias "GetShortPathNameA" ( _
                        ByVal lpszLongPath As String, _
                        ByVal lpszShortPath As String, _
                        ByVal cchBuffer As Long) _
                    As Long

Public Declare Function SetCapture _
                            Lib "user32" ( _
                        ByVal hwnd As Long) _
                    As Long
Public Declare Function ReleaseCapture _
                            Lib "user32" () _
                    As Long


'=-=-=-=-=-=-=-=
'  Kernel32.dll
'=-=-=-=-=-=-=-=
Public Declare Function CreateDirectory _
                                Lib "kernel32" _
                                Alias "CreateDirectoryA" ( _
                            ByVal lpPathName As String, _
                            lpSecurityAttributes As SECURITY_ATTRIBUTES) _
                        As Long

Public Declare Function GetModuleHandle _
                                Lib "kernel32" _
                                Alias "GetModuleHandleA" ( _
                            ByVal lpModuleName As String) _
                         As Long
Public Declare Function GetTempPath _
                                Lib "kernel32" _
                                Alias "GetTempPathA" ( _
                            ByVal nBufferLength As Long, _
                            ByVal lpBuffer As String) _
                         As Long  ' Length of string

Public Declare Function GetLastError _
                                    Lib "kernel32" _
                                    () _
                            As Long
Public Declare Function FormatMessage _
                                    Lib "kernel32" _
                                    Alias "FormatMessageA" ( _
                                ByVal dwFlags As enumFormatMessageFlags, _
                                lpSource As Any, _
                                ByVal dwMessageId As Long, _
                                ByVal dwLanguageId As enumLanguageIDs, _
                                ByVal lpBuffer As String, _
                                ByVal nSize As Long, _
                                Arguments As Long) _
                            As Long
Public Declare Function GetVersionEx _
                                    Lib "kernel32" _
                                    Alias "GetVersionExA" ( _
                                lpVersionInformation As typeOSVERSIONINFO) _
                            As Long




'=-=-=-=-=-=-=-=
'  Shell32.dll
'=-=-=-=-=-=-=-=
Public Declare Sub SHAddToRecentDocs _
                            Lib "Shell32.dll" ( _
                        ByVal uFlags As enumAddRecentDocuments, _
                        ByVal pv As String)
Public Declare Function SHCreateDirectoryEx _
                                   Lib "Shell32.dll" ( _
                               ByVal hwnd As Long, _
                               ByRef sPath As String, _
                               ByRef tSecurityAttributes As SECURITY_ATTRIBUTES) _
                            As Integer
Public Declare Function ShellExecute _
                                    Lib "Shell32.dll" _
                                    Alias "ShellExecuteA" ( _
                                ByVal hwnd As Long, _
                                ByVal lpOperation As String, _
                                ByVal lpFile As String, _
                                ByVal lpParameters As String, _
                                ByVal lpDirectory As String, _
                                ByVal nShowCmd As enumShowWindow) _
                            As Long


Public Declare Function GetSysColor _
                                    Lib "user32" ( _
                                ByVal nIndex As Long) _
                            As Long


Public Declare Function SendMessage _
                                    Lib "user32" _
                                    Alias "SendMessageA" ( _
                                ByVal hwnd As Long, _
                                ByVal wMsg As Long, _
                                ByVal wParam As Long, _
                                lParam As Any) _
                            As Long

Public Declare Function SHAppBarMessage _
                                    Lib "Shell32.dll" ( _
                                ByVal dwMessage As Long, _
                                pData As APPBARDATA) _
                            As Long
                            

Public Declare Function GetDriveType _
                                    Lib "kernel32" _
                                    Alias "GetDriveTypeA" ( _
                                ByVal nDrive As String) _
                            As enumDriveTypes


Public Declare Function GetLongPathName _
                                    Lib "kernel32" _
                                    Alias "GetLongPathNameA" ( _
                                ByVal lpszShortPath As String, _
                                ByVal lpszLongPath As String, _
                                ByVal cchBuffer As Long) _
                            As Long



#If bSendArrayDll Then
Public Declare Function GetBufferFromVariantArray _
                                    Lib "SendArray.dll" ( _
                                pvarIn As Variant, _
                                pcbBuf As Long, _
                                pvarOut As Variant) _
                            As Long
Public Declare Function GetVariantArrayFromBuffer _
                                    Lib "SendArray.dll" ( _
                                ByVal cbBuf As Long, _
                                pvarIn As Variant, _
                                pvarOut As Variant) _
                            As Long
#End If


Public Declare Function LocalSize Lib "kernel32" (ByVal hMem As Long) As Long

Public Declare Function GetProcessHeap Lib "kernel32" () As Long

Public Declare Function HeapSize Lib "kernel32" (ByVal hHeap As Long, ByVal dwFlags As Long, lpMem As Any) As Long

Public Declare Function PathCompactPathEx _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathCompactPathExA" ( _
                                ByVal pszOut As String, _
                                ByVal pszSrc As String, _
                                ByVal cchMax As Long, _
                                ByVal dwFlags As Long) _
                            As Long

Public Declare Function PathIsNetworkPath _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathIsNetworkPathA" ( _
                                ByVal pszPath As String) _
                            As Boolean
                            
Public Declare Function PathIsDirectory _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathIsDirectoryA" ( _
                                ByVal pszPath As String) _
                            As Boolean

Public Declare Function PathIsDirectoryEmpty _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathIsDirectoryEmptyA" ( _
                                ByVal pszPath As String) _
                            As Boolean

Public Declare Function PathIsUNCServerShare _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathIsUNCServerShareA" ( _
                                ByVal pszPath As String) _
                            As Boolean

Public Declare Function PathIsUNCServer _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathIsUNCServerA" ( _
                                ByVal pszPath As String) _
                            As Boolean

Public Declare Function PathIsUNC _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathIsUNCA" ( _
                                ByVal pszPath As String) _
                            As Boolean

Public Declare Function PathStripToRoot _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathStripToRootA" ( _
                                ByVal pszPath As String) _
                            As Long
                                
Public Declare Function GetSystemMetrics _
                                    Lib "user32" ( _
                                ByVal nIndex As enumSystemMetrics) _
                            As Long

Public Declare Function CoCreateGuid _
                                    Lib "ole32.dll" ( _
                                pGUID As GUID) _
                            As Long

'Public Declare Function StringFromGUID2 _
'                                    Lib "ole32.dll" ( _
'                                pGUID As GUID, _
'                                ByVal PointerToString As Long, _
'                                ByVal MaxLength As Long) _
'                            As Long
Public Declare Function StringFromGUID2 _
                                    Lib "ole32.dll" ( _
                                pGUID As Any, _
                                ByVal PointerToString As Long, _
                                ByVal MaxLength As Long) _
                            As Long

Public Declare Function PathGetDriveNumber _
                                    Lib "SHLWAPI.DLL" _
                                    Alias "PathGetDriveNumberA" ( _
                                ByVal pszPath As String) _
                            As Long

Public Declare Function GetVolumeInformation _
                                    Lib "kernel32" _
                                    Alias "GetVolumeInformationA" ( _
                                ByVal lpRootPathName As String, _
                                ByVal lpVolumeNameBuffer As String, _
                                ByVal nVolumeNameSize As Long, _
                                lpVolumeSerialNumber As Long, _
                                lpMaximumComponentLength As Long, _
                                lpFileSystemFlags As Long, _
                                ByVal lpFileSystemNameBuffer As String, _
                                ByVal nFileSystemNameSize As Long) _
                            As Long



Public Declare Function RegCloseKey _
                                    Lib "advapi32.dll" ( _
                                ByVal hKey As enumRegHkeys) _
                            As Long
Public Declare Function RegConnectRegistry _
                                    Lib "advapi32.dll" _
                                    Alias "RegConnectRegistryA" ( _
                                ByVal lpMachineName As String, _
                                ByVal hKey As enumRegHkeys, _
                                phkResult As Long) _
                            As Long
Public Declare Function RegCreateKey _
                                    Lib "advapi32.dll" _
                                    Alias "RegCreateKeyA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal lpSubKey As String, _
                                phkResult As Long) _
                            As Long
Public Declare Function RegCreateKeyEx _
                                    Lib "advapi32.dll" _
                                    Alias "RegCreateKeyExA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal lpSubKey As String, _
                                ByVal Reserved As Long, _
                                ByVal lpClass As String, _
                                ByVal dwOptions As Long, _
                                ByVal samDesired As Long, _
                                lpSecurityAttributes As SECURITY_ATTRIBUTES, _
                                phkResult As Long, _
                                lpdwDisposition As Long) _
                            As Long
Public Declare Function RegDeleteKey _
                                    Lib "advapi32.dll" _
                                    Alias "RegDeleteKeyA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal lpSubKey As String) _
                            As Long
Public Declare Function RegDeleteValue _
                                    Lib "advapi32.dll" _
                                    Alias "RegDeleteValueA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal lpValueName As String) _
                            As Long
Public Declare Function RegEnumKey _
                                    Lib "advapi32.dll" _
                                    Alias "RegEnumKeyA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal dwIndex As Long, _
                                ByVal lpName As String, _
                                ByVal cbName As Long) _
                            As Long
Public Declare Function RegEnumKeyEx _
                                    Lib "advapi32.dll" _
                                    Alias "RegEnumKeyExA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal dwIndex As Long, _
                                ByVal lpName As String, _
                                lpcbName As Long, _
                                ByVal lpReserved As Long, _
                                ByVal lpClass As String, _
                                lpcbClass As Long, _
                                lpftLastWriteTime As FILETIME) _
                            As Long
Public Declare Function RegEnumValue Lib "advapi32.dll" Alias "RegEnumValueA" (ByVal hKey As Long, ByVal dwIndex As Long, ByVal lpValueName As String, lpcbValueName As Long, ByVal lpReserved As Long, lpType As Long, lpData As Byte, lpcbData As Long) As Long
Public Declare Function RegFlushKey Lib "advapi32.dll" (ByVal hKey As Long) As Long
Public Declare Function RegGetKeySecurity Lib "advapi32.dll" (ByVal hKey As Long, ByVal SecurityInformation As Long, pSecurityDescriptor As SECURITY_DESCRIPTOR, lpcbSecurityDescriptor As Long) As Long
Public Declare Function RegLoadKey Lib "advapi32.dll" Alias "RegLoadKeyA" (ByVal hKey As Long, ByVal lpSubKey As String, ByVal lpFile As String) As Long
Public Declare Function RegOpenKey Lib "advapi32.dll" Alias "RegOpenKeyA" (ByVal hKey As Long, ByVal lpSubKey As String, phkResult As Long) As Long
Public Declare Function RegOpenKeyEx Lib "advapi32.dll" Alias "RegOpenKeyExA" (ByVal hKey As Long, ByVal lpSubKey As String, ByVal ulOptions As Long, ByVal samDesired As Long, phkResult As Long) As Long
Public Declare Function RegNotifyChangeKeyValue Lib "advapi32.dll" (ByVal hKey As Long, ByVal bWatchSubtree As Long, ByVal dwNotifyFilter As Long, ByVal hEvent As Long, ByVal fAsynchronus As Long) As Long
Public Declare Function RegQueryInfoKey Lib "advapi32.dll" Alias "RegQueryInfoKeyA" (ByVal hKey As Long, ByVal lpClass As String, lpcbClass As Long, ByVal lpReserved As Long, lpcSubKeys As Long, lpcbMaxSubKeyLen As Long, lpcbMaxClassLen As Long, lpcValues As Long, lpcbMaxValueNameLen As Long, lpcbMaxValueLen As Long, lpcbSecurityDescriptor As Long, lpftLastWriteTime As FILETIME) As Long
Public Declare Function RegQueryValue _
                                    Lib "advapi32.dll" _
                                    Alias "RegQueryValueA" ( _
                                ByVal hKey As enumRegHkeys, _
                                ByVal lpSubKey As String, _
                                ByVal lpValue As String, _
                                lpcbValue As Long) _
                            As Long
Public Declare Function RegQueryValueEx Lib "advapi32.dll" Alias "RegQueryValueExA" (ByVal hKey As Long, ByVal lpValueName As String, ByVal lpReserved As Long, lpType As Long, lpData As Any, lpcbData As Long) As Long
Public Declare Function RegReplaceKey Lib "advapi32.dll" Alias "RegReplaceKeyA" (ByVal hKey As Long, ByVal lpSubKey As String, ByVal lpNewFile As String, ByVal lpOldFile As String) As Long
Public Declare Function RegRestoreKey Lib "advapi32.dll" Alias "RegRestoreKeyA" (ByVal hKey As Long, ByVal lpFile As String, ByVal dwFlags As Long) As Long
Public Declare Function RegSaveKey Lib "advapi32.dll" Alias "RegSaveKeyA" (ByVal hKey As Long, ByVal lpFile As String, lpSecurityAttributes As SECURITY_ATTRIBUTES) As Long
Public Declare Function RegSetKeySecurity Lib "advapi32.dll" (ByVal hKey As Long, ByVal SecurityInformation As Long, pSecurityDescriptor As SECURITY_DESCRIPTOR) As Long
Public Declare Function RegSetValue Lib "advapi32.dll" Alias "RegSetValueA" (ByVal hKey As Long, ByVal lpSubKey As String, ByVal dwType As Long, ByVal lpData As String, ByVal cbData As Long) As Long
Public Declare Function RegSetValueEx Lib "advapi32.dll" Alias "RegSetValueExA" (ByVal hKey As Long, ByVal lpValueName As String, ByVal Reserved As Long, ByVal dwType As Long, lpData As Any, ByVal cbData As Long) As Long
Public Declare Function RegUnLoadKey Lib "advapi32.dll" Alias "RegUnLoadKeyA" (ByVal hKey As Long, ByVal lpSubKey As String) As Long


Public Declare Function SetFileTime _
                                    Lib "kernel32" ( _
                                ByVal hFile As Long, _
                                lpCreationTime As FILETIME, _
                                lpLastAccessTime As FILETIME, _
                                lpLastWriteTime As FILETIME) _
                            As Long

Public Declare Function GetFileTime _
                                    Lib "kernel32" ( _
                                ByVal hFile As Long, _
                                lpCreationTime As FILETIME, _
                                lpLastAccessTime As FILETIME, _
                                lpLastWriteTime As FILETIME) _
                            As Long

Public Declare Function SystemTimeToFileTime _
                                    Lib "kernel32" ( _
                                lpSystemTime As SYSTEMTIME, _
                                lpFileTime As FILETIME) _
                            As Long

Public Declare Sub mouse_event _
                                    Lib "user32" ( _
                                ByVal dwFlags As enumMouseEvents, _
                                ByVal dx As Long, _
                                ByVal dY As Long, _
                                ByVal cButtons As Long, _
                                ByVal dwExtraInfo As Long)

Public Declare Function FindClose _
                                    Lib "kernel32" ( _
                                ByVal hFindFile As Long) _
                            As Long

#If Not bStandAloneControls Then
Public Declare Function DrawEdge _
                                    Lib "user32" ( _
                                ByVal hdc As Long, _
                                qrc As Rect, _
                                ByVal edge As enumBorderEdges, _
                                ByVal grfFlags As enumBorderFlags) _
                            As Long
#End If

Public Declare Function ScreenToClientAny _
                                    Lib "user32" ( _
                                ByVal hwnd As Long, _
                                lpPoint As Any) _
                            As Long

Public Declare Function MoveWindow _
                                    Lib "user32" ( _
                                ByVal hwnd As Long, _
                                ByVal X As Long, _
                                ByVal Y As Long, _
                                ByVal nWidth As Long, _
                                ByVal nHeight As Long, _
                                ByVal bRepaint As Long) _
                            As Long

Public Declare Function GetWindowLong _
                                    Lib "user32" _
                                    Alias "GetWindowLongA" ( _
                                ByVal hwnd As Long, _
                                ByVal nIndex As Long) _
                            As Long

Public Declare Function SetWindowLong _
                                    Lib "user32" _
                                    Alias "SetWindowLongA" ( _
                                ByVal hwnd As Long, _
                                ByVal nIndex As Long, _
                                ByVal dwNewLong As Long) _
                            As Long


Public Declare Function GetCapture _
                                    Lib "user32" () _
                            As Long


Public Declare Function BitBlt _
                                    Lib "gdi32" ( _
                                ByVal hDestDC As Long, _
                                ByVal X As Long, _
                                ByVal Y As Long, _
                                ByVal nWidth As Long, _
                                ByVal nHeight As Long, _
                                ByVal hSrcDC As Long, _
                                ByVal xSrc As Long, _
                                ByVal ySrc As Long, _
                                ByVal dwRop As enumBitBltOps) _
                            As Long




Public Declare Function DrawState Lib "user32" Alias "DrawStateA" _
        (ByVal hdc As Long, _
        ByVal hBrush As Long, _
        ByVal lpDrawStateProc As Long, _
        ByVal lParam As Long, _
        ByVal wParam As Long, _
        ByVal X As Long, _
        ByVal Y As Long, _
        ByVal cx As Long, _
        ByVal cy As Long, _
        ByVal fuFlags As Long) As Long


Public Declare Function SetWindowPos Lib "user32" (ByVal hwnd As Long, _
        ByVal hWndInsertAfter As Long, ByVal X As Long, ByVal Y As Long, _
        ByVal cx As Long, ByVal cy As Long, ByVal wFlags As Long) As Long



Public Declare Function DrawFocusRect Lib "user32" (ByVal hdc As Long, lpRect As Rect) As Long



Public Declare Function GetTextAlign _
                                Lib "gdi32" ( _
                            ByVal hdc As Long) _
                        As enumTextAlignment
Public Declare Function SetTextAlign _
                                Lib "gdi32" ( _
                            ByVal hdc As Long, _
                            ByVal wFlags As enumTextAlignment) _
                        As Long

Public Declare Function GetTempFileName Lib "kernel32" Alias "GetTempFileNameA" (ByVal lpszPath As String, ByVal lpPrefixString As String, ByVal wUnique As Long, ByVal lpTempFileName As String) As Long



Public Declare Function SHBrowseForFolder _
                                Lib "shell32" ( _
                            lpBI As BrowseInfo) _
                        As Long


Public Declare Function SHGetPathFromIDList _
                                Lib "shell32" ( _
                            ByVal pidList As Long, _
                            ByVal lpBuffer As String) _
                        As Long


Public Declare Sub CoTaskMemFree _
                                Lib "ole32.dll" ( _
                            ByVal hMem As Long)

Public Declare Function lstrcat _
                                Lib "kernel32" _
                                Alias "lstrcatA" ( _
                            ByVal lpString1 As String, _
                            ByVal lpString2 As String) _
                        As Long

Public Declare Function SHFileOperation _
                                Lib "Shell32.dll" _
                                Alias "SHFileOperationA" ( _
                            lpFileOp As SHFILEOPSTRUCT) _
                        As Long

Public Declare Function DrawText _
                                Lib "user32" _
                                Alias "DrawTextA" ( _
                            ByVal hdc As Long, _
                            ByVal lpStr As String, _
                            ByVal nCount As Long, _
                            lpRect As Rect, _
                            ByVal wFormat As Long) _
                        As Long
                        
Public Declare Function DrawTextEx _
                                Lib "user32" _
                                Alias "DrawTextExA" ( _
                            ByVal hdc As Long, _
                            ByVal lpsz As String, _
                            ByVal n As Long, _
                            lpRect As Rect, _
                            ByVal un As Long, _
                            lpDrawTextParams As DRAWTEXTPARAMS) _
                        As Long


Public Const CCHDEVICENAME = 32
Public Const CCHFORMNAME = 32


Public Type DEVMODE
        dmDeviceName As String * CCHDEVICENAME
        dmSpecVersion As Integer
        dmDriverVersion As Integer
        dmSize As Integer
        dmDriverExtra As Integer
        dmFields As Long
        dmOrientation As Integer
        dmPaperSize As Integer
        dmPaperLength As Integer
        dmPaperWidth As Integer
        dmScale As Integer
        dmCopies As Integer
        dmDefaultSource As Integer
        dmPrintQuality As Integer
        dmColor As Integer
        dmDuplex As Integer
        dmYResolution As Integer
        dmTTOption As Integer
        dmCollate As Integer
        dmFormName As String * CCHFORMNAME
        dmUnusedPadding As Integer
        dmBitsPerPel As Long
        dmPelsWidth As Long
        dmPelsHeight As Long
        dmDisplayFlags As Long
        dmDisplayFrequency As Long
End Type


Public Declare Function GetWindowRect Lib "user32" (ByVal hwnd As Long, lpRect As Rect) As Long
Public Declare Function DeleteDC Lib "gdi32" (ByVal hdc As Long) As Long
Public Declare Function CreateDCAsNull Lib "gdi32" Alias "CreateDCA" (ByVal lpDriverName As String, lpDeviceName As Any, lpOutput As Any, lpInitData As Any) As Long
Public Declare Function CreateDC Lib "gdi32" Alias "CreateDCA" (ByVal lpDriverName As String, ByVal lpDeviceName As String, ByVal lpOutput As String, lpInitData As DEVMODE) As Long
Public Declare Function GetDC Lib "user32" (ByVal hwnd As Long) As Long
Public Declare Function GetDesktopWindow Lib "user32" () As Long






Public Declare Function CreateFile _
                            Lib "kernel32" _
                            Alias "CreateFileA" ( _
                        ByVal lpFileName As String, _
                        ByVal dwDesiredAccess As enumFileDesiredAccess, _
                        ByVal dwShareMode As enumFileShareMode, _
                        lpSecurityAttributes As Any, _
                        ByVal dwCreationDisposition As enumFileCreateDisposition, _
                        ByVal dwFlagsAndAttributes As Long, _
                        ByVal hTemplateFile As Long) _
                    As Long


Public Declare Function GetFileAttributesEx _
                            Lib "kernel32" _
                            Alias "GetFileAttributesExW" ( _
                        ByVal lpFileName As String, _
                        fInfoLevelId As GET_FILEEX_INFO_LEVELS, _
                        lpFileInformation As WIN32_FILE_ATTRIBUTE_DATA) _
                    As Boolean


Public Declare Function CreateMappedBitmap _
                            Lib "comctl32.dll" ( _
                        ByVal hInstance As Long, _
                        ByVal idBitmap As Long, _
                        ByVal wFlags As Long, _
                        lpColorMap As Any, _
                        ByVal iNumMaps As Long) _
                    As Long

Public Declare Function OleCreatePictureIndirect _
                            Lib "olepro32.dll" ( _
                        desc As PictDesc, _
                        RefIID As IID, _
                        ByVal fPictureOwnsHandle As Long, _
                        IPic As IPicture) _
                    As Long




'Public Declare Function DrawState _
'                            Lib "user32" _
'                            Alias "DrawStateA" ( _
'                        ByVal hDC As Long, _
'                        ByVal hBrush As Long, _
'                        ByVal lpDrawStateProc As Long, _
'                        ByVal lParam As Long, _
'                        ByVal wParam As Long, _
'                        ByVal n1 As Long, _
'                        ByVal n2 As Long, _
'                        ByVal n3 As Long, _
'                        ByVal n4 As Long, _
'                        ByVal un As Long) _
'                    As Long



Public Enum enumDrawIcon
    DI_MASK = &H1
    DI_IMAGE = &H2
    DI_NORMAL = &H3
    DI_COMPAT = &H4
    DI_DEFAULTSIZE = &H8
End Enum
Public Declare Function DrawIconEx _
                            Lib "user32" ( _
                        ByVal hdc As Long, _
                        ByVal xLeft As Long, _
                        ByVal yTop As Long, _
                        ByVal hIcon As Long, _
                        ByVal cxWidth As Long, _
                        ByVal cyWidth As Long, _
                        ByVal istepIfAniCur As Long, _
                        ByVal hbrFlickerFreeDraw As Long, _
                        ByVal diFlags As Long) _
                    As Long
Public Declare Function DrawStateString _
                            Lib "user32" _
                            Alias "DrawStateA" ( _
                        ByVal hdc As Long, _
                        ByVal hBrush As Long, _
                        ByVal lpDrawStateProc As Long, _
                        ByVal lpString As String, _
                        ByVal cbStringLen As Long, _
                        ByVal X As Long, _
                        ByVal Y As Long, _
                        ByVal cx As Long, _
                        ByVal cy As Long, _
                        ByVal fuFlags As Long) _
                    As Long


Public Declare Function SetFocus _
                            Lib "user32" ( _
                        ByVal hwnd As Long) _
                    As Long



Public Declare Function SetForegroundWindow Lib "user32" (ByVal hwnd As Long) As Long



Public Declare Function GetLocaleInfo _
                                Lib "kernel32" _
                                Alias "GetLocaleInfoA" ( _
                            ByVal Locale As Long, _
                            ByVal LCType As enumLocaleInfoTypes, _
                            ByVal lpLCData As String, _
                            ByVal cchData As Long) _
                        As Long
Public Declare Function SetLocaleInfo _
                                Lib "kernel32" _
                                Alias "SetLocaleInfoA" ( _
                            ByVal Locale As Long, _
                            ByVal LCType As enumLocaleInfoTypes, _
                            ByVal lpLCData As String) _
                        As Long
Public Declare Function GetSystemDefaultLCID _
                                Lib "kernel32" () _
                        As Long





Public Declare Function GetTextFace _
                                Lib "gdi32" _
                                Alias "GetTextFaceA" ( _
                            ByVal hdc As Long, _
                            ByVal nCount As Long, _
                            ByVal lpFacename As String) _
                        As Long

Public Declare Function GetTextMetrics _
                                Lib "gdi32" _
                                Alias "GetTextMetricsA" ( _
                            ByVal hdc As Long, _
                            lpMetrics As TEXTMETRIC) _
                        As Long

Public Declare Function GetDeviceCaps _
                                Lib "gdi32" ( _
                            ByVal hdc As Long, _
                            ByVal nIndex As Long) _
                        As Long

Public Declare Function MulDiv _
                                Lib "kernel32" ( _
                            ByVal nNumber As Long, _
                            ByVal nNumerator As Long, _
                            ByVal nDenominator As Long) _
                        As Long

Public Declare Function SelectObject _
                                Lib "gdi32" ( _
                            ByVal hdc As Long, _
                            ByVal hObject As Long) _
                        As Long
Public Declare Function CreateFontIndirect _
                                Lib "gdi32" _
                                Alias "CreateFontIndirectA" ( _
                            lpLogFont As LOGFONT) _
                        As Long

Public Declare Function SetTextColor _
                                Lib "gdi32" ( _
                            ByVal hdc As Long, _
                            ByVal crColor As Long) _
                        As Long

Public Declare Function GetTextColor _
                                Lib "gdi32" ( _
                            ByVal hdc As Long) _
                        As Long

'
'Public Declare Function SetTextAlign _
'                                Lib "gdi32" ( _
'                            ByVal hdc As Long, _
'                            ByVal wFlags As Long) _
'                        As Long
'Public Declare Function GetTextAlign _
'                                Lib "gdi32" ( _
'                            ByVal hdc As Long) _
'                        As Long

Public Const LF_FACESIZE = 32

Public Type LOGFONT
        lfHeight As Long
        lfWidth As Long
        lfEscapement As Long
        lfOrientation As Long
        lfWeight As Long
        lfItalic As Byte
        lfUnderline As Byte
        lfStrikeOut As Byte
        lfCharSet As Byte
        lfOutPrecision As Byte
        lfClipPrecision As Byte
        lfQuality As Byte
        lfPitchAndFamily As Byte
        lfFaceName(1 To LF_FACESIZE) As Byte
End Type


Public Type TEXTMETRIC
    tmHeight As Long
    tmAscent As Long
    tmDescent As Long
    tmInternalLeading As Long
    tmExternalLeading As Long
    tmAveCharWidth As Long
    tmMaxCharWidth As Long
    tmWeight As Long
    tmOverhang As Long
    tmDigitizedAspectX As Long
    tmDigitizedAspectY As Long
    tmFirstChar As Byte
    tmLastChar As Byte
    tmDefaultChar As Byte
    tmBreakChar As Byte
    tmItalic As Byte
    tmUnderlined As Byte
    tmStruckOut As Byte
    tmPitchAndFamily As Byte
    tmCharSet As Byte
End Type

Public Enum enumDeviceCaps
    LOGPIXELSX = 88        '  Logical pixels/inch in X
    LOGPIXELSY = 90        '  Logical pixels/inch in Y
    BITSPIXEL = 12         '  Number of bits per pixel
End Enum

Public Enum enumTMPF
    TMPF_DEVICE = &H8
    TMPF_FIXED_PITCH = &H1
    TMPF_TRUETYPE = &H4
    TMPF_VECTOR = &H2
End Enum



Public Declare Function GetParent Lib "user32" (ByVal hwnd As Long) As Long

